/**
 * Glintr Engage — system template catalog + default sequences.
 *
 * Every template listed here is available across the platform. Tenants
 * (Brand Owners) override by inserting their own row keyed on the same
 * `template_key` with a `brand_id`.
 */

import type { EngageChannel, EngageSequenceStep, EngageTemplateCategory } from "./types";

export interface SystemTemplateSpec {
  key: string;
  name: string;
  channel: EngageChannel;
  category: EngageTemplateCategory;
  subject: string;
  preview: string;
  headline: string;
  body: string;
  cta_label?: string;
  cta_url?: string;
}

/** All shipped system templates keyed by stable `template_key`. */
export const SYSTEM_TEMPLATES: SystemTemplateSpec[] = [
  // Onboarding / account
  { key: "welcome", name: "Welcome", channel: "email", category: "onboarding",
    subject: "Welcome to {{brand_name}}, {{first_name}}",
    preview: "Your learning journey starts now",
    headline: "Welcome to {{brand_name}}",
    body: "Hi {{first_name}},\n\nWelcome aboard. You now have access to the entire {{brand_name}} learning platform — programs, live classes, AI tools, and career support.\n\nTake the next step and pick your first program.",
    cta_label: "Explore Programs", cta_url: "{{app_url}}/programs" },
  { key: "verify_email", name: "Verify Email", channel: "email", category: "system",
    subject: "Verify your email on {{brand_name}}",
    preview: "One click to activate your account",
    headline: "Verify your email",
    body: "Hi {{first_name}},\n\nConfirm this email address to activate your account and unlock the full platform.",
    cta_label: "Verify email", cta_url: "{{verify_url}}" },
  { key: "verify_reminder", name: "Verify Email Reminder", channel: "email", category: "onboarding",
    subject: "Reminder: verify your {{brand_name}} email",
    preview: "It only takes a second",
    headline: "Still need to verify?",
    body: "Hi {{first_name}}, we noticed your email is not verified yet. Verifying unlocks certificates, live classes, and payments.",
    cta_label: "Verify now", cta_url: "{{verify_url}}" },
  { key: "password_reset", name: "Password Reset", channel: "email", category: "system",
    subject: "Reset your {{brand_name}} password",
    preview: "Reset link inside",
    headline: "Reset your password",
    body: "Click the button below to choose a new password. If you didn't request this, ignore this email.",
    cta_label: "Reset password", cta_url: "{{reset_url}}" },
  { key: "login_alert", name: "Login Alert", channel: "email", category: "system",
    subject: "New sign-in to your {{brand_name}} account",
    preview: "Was this you?",
    headline: "New sign-in detected",
    body: "We noticed a sign-in from {{device}} in {{location}} on {{signin_time}}. If this wasn't you, secure your account now.",
    cta_label: "Secure account", cta_url: "{{app_url}}/security" },
  { key: "new_device_login", name: "New Device Login", channel: "email", category: "system",
    subject: "New device signed into your account",
    preview: "A new device just accessed your account",
    headline: "New device signed in",
    body: "A new device ({{device}}) signed into your account on {{signin_time}}. If this was you, no action needed.",
    cta_label: "Review devices", cta_url: "{{app_url}}/security" },
  { key: "account_created", name: "Account Created", channel: "email", category: "onboarding",
    subject: "Your {{brand_name}} account is ready",
    preview: "Sign in to get started",
    headline: "Your account is ready",
    body: "Your {{brand_name}} account has been created. Sign in and explore.",
    cta_label: "Sign in", cta_url: "{{app_url}}/auth" },
  { key: "profile_reminder", name: "Complete Your Profile", channel: "email", category: "onboarding",
    subject: "Finish setting up your profile",
    preview: "Better recommendations in 60 seconds",
    headline: "Complete your profile",
    body: "Add your goals and interests so we can recommend the right programs, mentors, and internships.",
    cta_label: "Complete profile", cta_url: "{{app_url}}/my/profile" },

  // Learning
  { key: "course_enrollment", name: "Course Enrollment", channel: "email", category: "transactional",
    subject: "You're enrolled in {{course_title}}",
    preview: "Access your program now",
    headline: "You're in!",
    body: "You've been enrolled in {{course_title}}. Head to your dashboard to start learning.",
    cta_label: "Open course", cta_url: "{{course_url}}" },
  { key: "course_started", name: "Course Started", channel: "email", category: "nurture",
    subject: "You started {{course_title}} — keep going",
    preview: "Your streak begins here",
    headline: "Great start, {{first_name}}!",
    body: "You've begun {{course_title}}. Consistency wins — aim for 20 minutes today.",
    cta_label: "Resume", cta_url: "{{course_url}}" },
  { key: "course_progress", name: "Course Progress", channel: "email", category: "nurture",
    subject: "You're {{progress_pct}}% through {{course_title}}",
    preview: "Keep the momentum",
    headline: "You're on a roll",
    body: "You've completed {{progress_pct}}% of {{course_title}}. Just a few more sessions to your certificate.",
    cta_label: "Continue learning", cta_url: "{{course_url}}" },
  { key: "course_completion", name: "Course Completion", channel: "email", category: "transactional",
    subject: "Congratulations on completing {{course_title}}",
    preview: "Your certificate is ready",
    headline: "You did it!",
    body: "You've completed {{course_title}}. Download your certificate and share your achievement.",
    cta_label: "Download certificate", cta_url: "{{certificate_url}}" },
  { key: "certificate_ready", name: "Certificate Ready", channel: "email", category: "transactional",
    subject: "Your {{course_title}} certificate is ready",
    preview: "Download and share",
    headline: "Your certificate is here",
    body: "Your certificate for {{course_title}} is ready to download and share on LinkedIn.",
    cta_label: "Get certificate", cta_url: "{{certificate_url}}" },
  { key: "internship_assigned", name: "Internship Assigned", channel: "email", category: "transactional",
    subject: "You've been assigned an internship: {{internship_title}}",
    preview: "Real-world experience starts now",
    headline: "Internship assigned",
    body: "You've been placed in {{internship_title}}. Your mentor is {{mentor_name}}.",
    cta_label: "View internship", cta_url: "{{internship_url}}" },
  { key: "workshop_registration", name: "Workshop Registration", channel: "email", category: "transactional",
    subject: "You're registered for {{workshop_title}}",
    preview: "Save the date",
    headline: "See you at the workshop",
    body: "Your seat is confirmed for {{workshop_title}} on {{workshop_date}}. Join link inside.",
    cta_label: "Add to calendar", cta_url: "{{workshop_url}}" },
  { key: "live_class_reminder", name: "Live Class Reminder", channel: "email", category: "notification",
    subject: "Live class in 1 hour: {{class_title}}",
    preview: "Join link inside",
    headline: "Your live class starts soon",
    body: "{{class_title}} with {{instructor_name}} begins at {{class_time}}.",
    cta_label: "Join now", cta_url: "{{join_url}}" },
  { key: "assignment_reminder", name: "Assignment Reminder", channel: "email", category: "notification",
    subject: "Assignment due: {{assignment_title}}",
    preview: "Don't miss the deadline",
    headline: "Assignment due soon",
    body: "{{assignment_title}} is due on {{due_date}}. Submit before the deadline to keep your progress.",
    cta_label: "Submit", cta_url: "{{assignment_url}}" },
  { key: "quiz_reminder", name: "Quiz Reminder", channel: "email", category: "notification",
    subject: "Quiz reminder: {{quiz_title}}",
    preview: "Attempt before it closes",
    headline: "Quiz waiting for you",
    body: "The quiz {{quiz_title}} closes on {{close_date}}. Test what you've learned.",
    cta_label: "Take quiz", cta_url: "{{quiz_url}}" },

  // Payments
  { key: "payment_success", name: "Payment Success", channel: "email", category: "transactional",
    subject: "Payment received — thank you",
    preview: "Your enrollment is confirmed",
    headline: "Payment confirmed",
    body: "We received your payment of {{amount}} for {{item_name}}. Access is now active.",
    cta_label: "View details", cta_url: "{{invoice_url}}" },
  { key: "payment_failed", name: "Payment Failed", channel: "email", category: "transactional",
    subject: "Payment failed for {{item_name}}",
    preview: "Retry to complete enrollment",
    headline: "Your payment didn't go through",
    body: "The payment of {{amount}} for {{item_name}} failed. Retry with a different method to complete enrollment.",
    cta_label: "Retry payment", cta_url: "{{retry_url}}" },
  { key: "invoice", name: "Invoice", channel: "email", category: "transactional",
    subject: "Invoice #{{invoice_number}} from {{brand_name}}",
    preview: "Your invoice is attached",
    headline: "Invoice #{{invoice_number}}",
    body: "Please find your invoice for {{amount}} attached. Thank you for your business.",
    cta_label: "Download invoice", cta_url: "{{invoice_url}}" },
  { key: "refund_processed", name: "Refund Processed", channel: "email", category: "transactional",
    subject: "Refund processed for {{item_name}}",
    preview: "Money on its way",
    headline: "Your refund is on the way",
    body: "We've processed a refund of {{amount}} for {{item_name}}. It should reach your account within 5–7 business days.",
    cta_label: "View details", cta_url: "{{refund_url}}" },
  { key: "subscription_renewal", name: "Subscription Renewal", channel: "email", category: "transactional",
    subject: "Your {{plan_name}} plan renews on {{renewal_date}}",
    preview: "No action required",
    headline: "Upcoming renewal",
    body: "Your {{plan_name}} plan renews automatically on {{renewal_date}} for {{amount}}.",
    cta_label: "Manage plan", cta_url: "{{billing_url}}" },
  { key: "subscription_expiry", name: "Subscription Expiring", channel: "email", category: "transactional",
    subject: "Your {{plan_name}} expires soon",
    preview: "Renew to keep access",
    headline: "Your plan is expiring",
    body: "Your {{plan_name}} plan expires on {{expiry_date}}. Renew to keep uninterrupted access.",
    cta_label: "Renew now", cta_url: "{{billing_url}}" },
  { key: "coupon_email", name: "Coupon", channel: "email", category: "promotional",
    subject: "A special {{discount_pct}}% off just for you",
    preview: "Use code {{coupon_code}}",
    headline: "Here's {{discount_pct}}% off",
    body: "Apply code {{coupon_code}} at checkout. Valid until {{expires_at}}.",
    cta_label: "Shop programs", cta_url: "{{app_url}}/programs" },

  // Referrals
  { key: "referral_invitation", name: "Referral Invitation", channel: "email", category: "promotional",
    subject: "{{referrer_name}} invited you to {{brand_name}}",
    preview: "Claim your welcome reward",
    headline: "You're invited",
    body: "{{referrer_name}} thinks you'd love {{brand_name}}. Sign up with their link and both of you unlock rewards.",
    cta_label: "Accept invite", cta_url: "{{invite_url}}" },
  { key: "referral_reward", name: "Referral Reward", channel: "email", category: "transactional",
    subject: "You earned a {{reward_type}} reward",
    preview: "{{referred_name}} just joined",
    headline: "Your referral came through",
    body: "{{referred_name}} joined {{brand_name}} using your link. Your {{reward_type}} reward is credited.",
    cta_label: "See rewards", cta_url: "{{rewards_url}}" },

  // Invitations
  { key: "brand_invitation", name: "Brand Owner Invitation", channel: "email", category: "system",
    subject: "You're invited to launch your brand on Glintr",
    preview: "Own your academy end-to-end",
    headline: "Launch your brand",
    body: "You've been invited to start your own white-label academy on Glintr. Set up your storefront in minutes.",
    cta_label: "Set up brand", cta_url: "{{invite_url}}" },
  { key: "instructor_invitation", name: "Instructor Invitation", channel: "email", category: "system",
    subject: "You're invited to teach on {{brand_name}}",
    preview: "Share your expertise",
    headline: "Teach on {{brand_name}}",
    body: "You've been invited to join {{brand_name}} as an instructor. Create your instructor profile and start teaching.",
    cta_label: "Accept invite", cta_url: "{{invite_url}}" },
  { key: "sales_partner_invitation", name: "Sales Partner Invitation", channel: "email", category: "system",
    subject: "Partner with {{brand_name}} — flat 70% revenue share",
    preview: "Earn as you refer",
    headline: "Partner with {{brand_name}}",
    body: "You've been invited to become a Sales Partner. Refer learners and earn a flat 70% revenue share.",
    cta_label: "Accept invite", cta_url: "{{invite_url}}" },
  { key: "admin_invitation", name: "Admin Invitation", channel: "email", category: "system",
    subject: "Admin access invitation for {{brand_name}}",
    preview: "Accept your admin role",
    headline: "You've been made an admin",
    body: "You've been granted admin access to {{brand_name}}. Sign in to manage the platform.",
    cta_label: "Accept access", cta_url: "{{invite_url}}" },

  // Leads / support
  { key: "lead_assigned", name: "Lead Assigned", channel: "email", category: "notification",
    subject: "New lead assigned: {{lead_name}}",
    preview: "Reach out within the hour for best results",
    headline: "New lead assigned",
    body: "{{lead_name}} was just assigned to you. Score: {{lead_score}}. Reach out fast for the best conversion rate.",
    cta_label: "Open lead", cta_url: "{{lead_url}}" },
  { key: "lead_converted", name: "Lead Converted", channel: "email", category: "notification",
    subject: "{{lead_name}} converted",
    preview: "Congrats on the win",
    headline: "You closed a lead",
    body: "{{lead_name}} just enrolled in {{course_title}}. Great work.",
    cta_label: "View conversion", cta_url: "{{lead_url}}" },
  { key: "support_ticket_created", name: "Support Ticket Created", channel: "email", category: "transactional",
    subject: "Ticket #{{ticket_id}} received",
    preview: "We'll be in touch shortly",
    headline: "Ticket received",
    body: "Thanks for reaching out. We've opened ticket #{{ticket_id}} and will reply within one business day.",
    cta_label: "View ticket", cta_url: "{{ticket_url}}" },
  { key: "support_ticket_resolved", name: "Support Ticket Resolved", channel: "email", category: "transactional",
    subject: "Ticket #{{ticket_id}} resolved",
    preview: "How did we do?",
    headline: "Your ticket is resolved",
    body: "Your ticket #{{ticket_id}} has been marked resolved. Reply to reopen if the issue persists.",
    cta_label: "Rate support", cta_url: "{{ticket_url}}" },

  // Newsletters + marketing
  { key: "newsletter", name: "Newsletter", channel: "email", category: "newsletter",
    subject: "{{brand_name}} — this week in learning",
    preview: "The best of the week",
    headline: "This week in learning",
    body: "Here's what's new on {{brand_name}}: fresh courses, live sessions, and career updates.",
    cta_label: "Read more", cta_url: "{{app_url}}/blog" },
  { key: "monthly_updates", name: "Monthly Updates", channel: "email", category: "newsletter",
    subject: "{{brand_name}} — {{month}} recap",
    preview: "What you missed this month",
    headline: "{{month}} in review",
    body: "Here's everything that happened on {{brand_name}} this month.",
    cta_label: "See updates", cta_url: "{{app_url}}/blog" },
  { key: "weekly_updates", name: "Weekly Updates", channel: "email", category: "newsletter",
    subject: "Weekly learning digest",
    preview: "Top picks for you",
    headline: "Your weekly digest",
    body: "New courses, top instructors, and career-boosting reads — curated for you.",
    cta_label: "Browse digest", cta_url: "{{app_url}}/blog" },
  { key: "feature_release", name: "Feature Release", channel: "email", category: "promotional",
    subject: "New on {{brand_name}}: {{feature_name}}",
    preview: "See what's new",
    headline: "Introducing {{feature_name}}",
    body: "{{feature_description}}",
    cta_label: "Try it", cta_url: "{{feature_url}}" },
  { key: "new_course_launch", name: "New Course Launch", channel: "email", category: "promotional",
    subject: "New course: {{course_title}}",
    preview: "Early-bird pricing inside",
    headline: "{{course_title}} is live",
    body: "Our new program {{course_title}} just launched. Enroll during early-bird to save.",
    cta_label: "Enroll", cta_url: "{{course_url}}" },
  { key: "special_offer", name: "Special Offer", channel: "email", category: "promotional",
    subject: "Special offer: {{offer_headline}}",
    preview: "Limited time",
    headline: "{{offer_headline}}",
    body: "{{offer_body}}",
    cta_label: "Claim offer", cta_url: "{{offer_url}}" },
  { key: "festival_offer", name: "Festival Offer", channel: "email", category: "promotional",
    subject: "{{festival}} special — {{discount_pct}}% off",
    preview: "Celebrate with learning",
    headline: "Happy {{festival}}",
    body: "Enjoy {{discount_pct}}% off across all programs this {{festival}}. Use code {{coupon_code}}.",
    cta_label: "Shop offers", cta_url: "{{app_url}}/programs" },
  { key: "flash_sale", name: "Flash Sale", channel: "email", category: "promotional",
    subject: "Flash sale — ends in 24 hours",
    preview: "Save up to {{discount_pct}}%",
    headline: "24-hour flash sale",
    body: "Grab up to {{discount_pct}}% off across our top programs. Ends midnight tonight.",
    cta_label: "Shop sale", cta_url: "{{app_url}}/programs" },
  { key: "career_tips", name: "Career Tips", channel: "email", category: "newsletter",
    subject: "Career tip: {{tip_headline}}",
    preview: "Actionable advice inside",
    headline: "{{tip_headline}}",
    body: "{{tip_body}}",
    cta_label: "Read more", cta_url: "{{tip_url}}" },
  { key: "placement_updates", name: "Placement Updates", channel: "email", category: "newsletter",
    subject: "Placement updates from {{brand_name}}",
    preview: "Fresh hiring news",
    headline: "New placement drives",
    body: "See who's hiring this week and land your dream role.",
    cta_label: "See drives", cta_url: "{{app_url}}/placements" },
  { key: "success_stories", name: "Success Stories", channel: "email", category: "newsletter",
    subject: "Meet {{student_name}} — {{outcome}}",
    preview: "Real learner, real result",
    headline: "Success story: {{student_name}}",
    body: "{{story_body}}",
    cta_label: "Read full story", cta_url: "{{story_url}}" },

  // Abandonment
  { key: "abandoned_enrollment_1", name: "Abandoned Enrollment 1", channel: "email", category: "nurture",
    subject: "You forgot something at {{brand_name}}",
    preview: "Your program is still available",
    headline: "Ready to pick up where you left off?",
    body: "You were checking out {{course_title}} but didn't complete enrollment. Your spot is still open.",
    cta_label: "Complete enrollment", cta_url: "{{course_url}}" },
  { key: "abandoned_enrollment_2", name: "Abandoned Enrollment 2", channel: "email", category: "nurture",
    subject: "3 reasons to enroll in {{course_title}}",
    preview: "Why learners choose this program",
    headline: "Why {{course_title}}",
    body: "Industry mentors. Real projects. Placement support. Here's why {{course_title}} is worth your time.",
    cta_label: "See details", cta_url: "{{course_url}}" },
  { key: "abandoned_enrollment_discount", name: "Abandoned Enrollment — Discount", channel: "email", category: "promotional",
    subject: "A little something to help you start",
    preview: "{{discount_pct}}% off {{course_title}}",
    headline: "Take {{discount_pct}}% off",
    body: "Use code {{coupon_code}} to unlock {{discount_pct}}% off {{course_title}}. Valid for 48 hours.",
    cta_label: "Claim discount", cta_url: "{{course_url}}" },
  { key: "abandoned_enrollment_testimonials", name: "Abandoned Enrollment — Testimonials", channel: "email", category: "nurture",
    subject: "What learners say about {{course_title}}",
    preview: "Hear from real students",
    headline: "Real learners, real outcomes",
    body: "Read what past students have to say about {{course_title}}.",
    cta_label: "Read testimonials", cta_url: "{{course_url}}" },
  { key: "abandoned_enrollment_final", name: "Abandoned Enrollment — Final Offer", channel: "email", category: "promotional",
    subject: "Last chance for {{course_title}}",
    preview: "Enrollment closes soon",
    headline: "Final call",
    body: "Enrollment for {{course_title}} closes on {{close_date}}. Don't miss it.",
    cta_label: "Enroll now", cta_url: "{{course_url}}" },

  // Nurture / recommendations
  { key: "welcome_back", name: "Welcome Back", channel: "email", category: "nurture",
    subject: "Welcome back, {{first_name}}",
    preview: "New programs picked for you",
    headline: "Great to see you again",
    body: "Here are new courses, internships, certifications, AI tools, and career paths picked for you.",
    cta_label: "Explore picks", cta_url: "{{app_url}}/my/discover" },
  { key: "signup_benefits", name: "Benefits of Joining", channel: "email", category: "onboarding",
    subject: "5 reasons learners choose {{brand_name}}",
    preview: "See what you get",
    headline: "Why {{brand_name}}",
    body: "AI-first curriculum. Real internships. Career support. And more.",
    cta_label: "See benefits", cta_url: "{{app_url}}/why-us" },
  { key: "popular_courses", name: "Popular Courses", channel: "email", category: "nurture",
    subject: "Trending on {{brand_name}} this week",
    preview: "What everyone's learning",
    headline: "Trending programs",
    body: "See the most-enrolled programs on {{brand_name}} this week.",
    cta_label: "Browse trending", cta_url: "{{app_url}}/programs?sort=popular" },
  { key: "limited_time_offer", name: "Limited Time Offer", channel: "email", category: "promotional",
    subject: "Limited time: {{offer_headline}}",
    preview: "Ends soon",
    headline: "{{offer_headline}}",
    body: "{{offer_body}}",
    cta_label: "Grab offer", cta_url: "{{offer_url}}" },
  { key: "personalized_recs", name: "Personalized Recommendations", channel: "email", category: "nurture",
    subject: "Picked for you: {{course_title}}",
    preview: "Based on your goals",
    headline: "Programs that match your goals",
    body: "Because you're interested in {{interest_area}}, we picked these programs for you.",
    cta_label: "See recommendations", cta_url: "{{app_url}}/my/discover" },
];

/** Templates grouped by category — used for the admin templates UI. */
export const TEMPLATE_CATEGORIES: Array<{ id: EngageTemplateCategory; label: string; description: string }> = [
  { id: "transactional", label: "Transactional", description: "Triggered by a specific event for a specific recipient" },
  { id: "onboarding", label: "Onboarding", description: "Welcome, activate, and orient new users" },
  { id: "nurture", label: "Nurture", description: "Drip and lifecycle emails" },
  { id: "promotional", label: "Promotional", description: "Offers, launches, and sales" },
  { id: "newsletter", label: "Newsletter", description: "Recurring digests and updates" },
  { id: "notification", label: "Notification", description: "Reminders and status alerts" },
  { id: "system", label: "System", description: "Security and account maintenance" },
];

/** Default sequences seeded once per platform. */
export interface SystemSequenceSpec {
  key: string;
  name: string;
  description: string;
  trigger_event: string;
  audience: string;
  steps: EngageSequenceStep[];
}

export const SYSTEM_SEQUENCES: SystemSequenceSpec[] = [
  {
    key: "signup_nurture",
    name: "Sign-up nurture (30 days)",
    description: "Welcomes new users, reminds them to verify, then walks them through platform value.",
    trigger_event: "user.signup",
    audience: "students",
    steps: [
      { delay_hours: 0, template_key: "welcome", channel: "email" },
      { delay_hours: 24, template_key: "verify_reminder", channel: "email", condition: { field: "email_verified", op: "!=", value: true } },
      { delay_hours: 48, template_key: "verify_reminder", channel: "email", condition: { field: "email_verified", op: "!=", value: true } },
      { delay_hours: 72, template_key: "verify_reminder", channel: "email", condition: { field: "email_verified", op: "!=", value: true } },
      { delay_hours: 168, template_key: "signup_benefits", channel: "email" },
      { delay_hours: 240, template_key: "popular_courses", channel: "email" },
      { delay_hours: 336, template_key: "limited_time_offer", channel: "email" },
      { delay_hours: 504, template_key: "success_stories", channel: "email" },
      { delay_hours: 720, template_key: "personalized_recs", channel: "email" },
    ],
  },
  {
    key: "returning_login",
    name: "Welcome back",
    description: "Fired when a user signs in after 14+ days of inactivity.",
    trigger_event: "login.returning",
    audience: "students",
    steps: [
      { delay_hours: 0, template_key: "welcome_back", channel: "email" },
    ],
  },
  {
    key: "abandoned_enrollment",
    name: "Abandoned enrollment",
    description: "Recovers a user who visited a course page but did not enroll.",
    trigger_event: "enrollment.abandoned",
    audience: "students",
    steps: [
      { delay_hours: 1, template_key: "abandoned_enrollment_1", channel: "email" },
      { delay_hours: 24, template_key: "abandoned_enrollment_2", channel: "email" },
      { delay_hours: 48, template_key: "abandoned_enrollment_discount", channel: "email" },
      { delay_hours: 96, template_key: "abandoned_enrollment_testimonials", channel: "email" },
      { delay_hours: 168, template_key: "abandoned_enrollment_final", channel: "email" },
    ],
  },
  {
    key: "course_completed_upsell",
    name: "Course completed — next step",
    description: "Nurtures learners who complete a course toward an advanced program.",
    trigger_event: "course.completed",
    audience: "students",
    steps: [
      { delay_hours: 0, template_key: "certificate_ready", channel: "email" },
      { delay_hours: 48, template_key: "personalized_recs", channel: "email" },
    ],
  },
];

/** Notification categories exposed in the preference center. */
export const NOTIFICATION_CATEGORIES = [
  { id: "transactional", label: "Account & Transactions", locked: true, description: "Order receipts, security alerts, password resets. Can't be turned off." },
  { id: "onboarding", label: "Getting Started", locked: false, description: "Tips to help you get the most out of the platform." },
  { id: "newsletter", label: "Weekly Digest", locked: false, description: "Curated learning picks each week." },
  { id: "promotional", label: "Offers & Promotions", locked: false, description: "Discounts, festivals, and flash sales." },
  { id: "notification", label: "Class & Assignment Reminders", locked: false, description: "Live class, quiz, and assignment reminders." },
  { id: "career_tips", label: "Career Tips", locked: false, description: "Placement updates and career-boosting advice." },
] as const;

/** Full list of trigger events the sequence engine understands. */
export const TRIGGER_EVENTS = [
  "user.signup",
  "user.verified",
  "login.returning",
  "profile.incomplete",
  "enrollment.abandoned",
  "enrollment.completed",
  "course.started",
  "course.progressed",
  "course.completed",
  "certificate.issued",
  "payment.success",
  "payment.failed",
  "subscription.renewed",
  "subscription.expiring",
  "referral.completed",
  "lead.assigned",
  "lead.converted",
  "support.opened",
  "support.resolved",
] as const;
