import type { PseoTemplateDef } from "./types";

// Every {var} in strings is replaced from the page variables map.

export const PSEO_TEMPLATES: PseoTemplateDef[] = [
  {
    id: "best-skill-course",
    label: "Best {Skill} Course",
    pageType: "course",
    description: "Ranked, comparison-style landing page for the best courses in a skill.",
    variables: [
      { key: "skill", label: "Skill", placeholder: "AI, Data Science, VLSI", required: true },
      { key: "year", label: "Year", placeholder: "2026" },
    ],
    titleTemplate: "Best {skill} Course in {year}: Curriculum, Fees, Placements | Glintr",
    descriptionTemplate:
      "Compare the best {skill} courses in {year} — curriculum depth, mentors, projects, placement support and fees. Pick the right {skill} program with Glintr.",
    slugTemplate: "best-{skill}-course",
    h1Template: "Best {skill} Courses in {year}",
    keywords: ["best {skill} course", "top {skill} training", "{skill} certification"],
    sectionPlan: [
      { heading: "What makes a great {skill} course", body: "A strong {skill} program balances fundamentals, applied projects, mentor access and career outcomes. Judge courses on curriculum depth, real-world projects, live mentor sessions and placement transparency — not just brand recall." },
      { heading: "How Glintr ranks {skill} courses", body: "Editors weigh curriculum coverage, project quality, mentor experience, placement data and learner reviews. Courses without transparent outcomes are excluded." },
      { heading: "What you will learn", body: "Modern {skill} programs move from foundations to production tooling.", bullets: ["Core concepts and terminology", "Hands-on projects with real datasets", "Portfolio-ready capstones", "Interview preparation and mock rounds"] },
      { heading: "Who should enroll", body: "Ideal for career switchers, engineering students, working professionals and freelancers who want structured {skill} training with career support." },
      { heading: "Career outcomes", body: "Graduates of quality {skill} programs move into analyst, engineer, associate and consultant roles across product, services and enterprise firms." },
    ],
    faqPlan: [
      { q: "What is the best {skill} course for beginners?", a: "A beginner-friendly {skill} course covers fundamentals, uses real projects and offers mentor access. Look for structured roadmaps and placement support." },
      { q: "How long does a {skill} course take?", a: "Most quality {skill} courses run 3–6 months full-track, with self-paced options extending the timeline based on weekly effort." },
      { q: "Is a {skill} certificate worth it?", a: "A {skill} certificate matters most when paired with strong projects and interview readiness. Employers weigh applied portfolios and clarity of concepts over certificates alone." },
    ],
  },
  {
    id: "how-to-learn-skill",
    label: "How to Learn {Skill}",
    pageType: "learning-path",
    description: "Step-by-step learning path for a skill with milestones and resources.",
    variables: [
      { key: "skill", label: "Skill", required: true },
      { key: "months", label: "Timeline (months)", placeholder: "6" },
    ],
    titleTemplate: "How to Learn {skill}: {months}-Month Roadmap for Beginners | Glintr",
    descriptionTemplate:
      "A {months}-month roadmap to learn {skill} from scratch — prerequisites, projects, milestones and job-ready portfolio. Written by Glintr mentors.",
    slugTemplate: "how-to-learn-{skill}",
    h1Template: "How to Learn {skill} in {months} Months",
    keywords: ["how to learn {skill}", "{skill} roadmap", "{skill} for beginners"],
    sectionPlan: [
      { heading: "Prerequisites", body: "You do not need prior experience to start {skill}, but comfort with basic math, logic and a scripting language shortens the ramp." },
      { heading: "Phase 1 — Foundations (Month 1–2)", body: "Build the mental model.", bullets: ["Understand core {skill} concepts and vocabulary", "Study 3 canonical worked examples", "Set up your local environment and tooling", "Ship one small starter project"] },
      { heading: "Phase 2 — Applied depth (Month 3–4)", body: "Move to real problems.", bullets: ["Work with production-shaped datasets or systems", "Reproduce 2 published projects end to end", "Study evaluation, testing and reliability", "Read one classic paper or textbook chapter weekly"] },
      { heading: "Phase 3 — Portfolio and interview (Month 5–{months})", body: "Convert learning into offers.", bullets: ["Ship one capstone that solves a real problem", "Write a public case study of your capstone", "Practice interview loops with mentors", "Apply to roles with a targeted portfolio"] },
      { heading: "Common mistakes to avoid", body: "Skipping fundamentals, hoarding tutorials without shipping, and copying projects without understanding them are the three fastest ways to stall." },
    ],
    faqPlan: [
      { q: "Can I learn {skill} without a technical background?", a: "Yes — many learners with non-technical backgrounds complete {skill} programs by starting with fundamentals and pairing every module with hands-on practice." },
      { q: "How many hours per week do I need to learn {skill}?", a: "Plan for 8–12 focused hours per week to complete the roadmap in {months} months. Consistency beats bursts." },
    ],
  },
  {
    id: "what-is-technology",
    label: "What is {Technology}",
    pageType: "technology-guide",
    description: "Definition-first educational page for a technology.",
    variables: [{ key: "technology", label: "Technology", required: true }],
    titleTemplate: "What is {technology}? Definition, How It Works, Uses | Glintr",
    descriptionTemplate: "A clear explanation of {technology} — what it is, how it works, where it is used, and how to start learning it. Written for beginners and professionals.",
    slugTemplate: "what-is-{technology}",
    h1Template: "What is {technology}?",
    keywords: ["what is {technology}", "{technology} explained", "{technology} definition"],
    sectionPlan: [
      { heading: "Quick definition", body: "{technology} is a field that combines core ideas from computer science, mathematics and engineering to solve a specific class of problems. This page explains what it means, how it works and how to start." },
      { heading: "How {technology} works", body: "At the heart of {technology} is a small set of ideas that combine into powerful systems. Understanding these building blocks first makes advanced topics easier to reason about." },
      { heading: "Where {technology} is used today", body: "Common applications span product, research and enterprise settings.", bullets: ["Consumer software features", "Business automation and analytics", "Scientific and industrial applications", "Emerging areas that expand every year"] },
      { heading: "Skills you need to work with {technology}", body: "Practitioners typically know a general-purpose programming language, the core concepts of {technology}, and enough system design to ship reliable software." },
      { heading: "How to start learning {technology}", body: "Pick a structured curriculum, ship one small project weekly, and pair theory with applied practice. Avoid tutorial-only paths." },
    ],
    faqPlan: [
      { q: "Is {technology} hard to learn?", a: "{technology} is approachable when studied in the right order. Learners with focused effort typically become productive within a few months." },
      { q: "Do I need advanced math for {technology}?", a: "Foundational math helps, but many practitioners work productively with high-school-level math and pick up advanced topics as needed." },
    ],
  },
  {
    id: "career-guide",
    label: "{Technology} Career Guide",
    pageType: "career-guide",
    description: "Career guide covering roles, skills and progression.",
    variables: [{ key: "technology", label: "Technology / Field", required: true }],
    titleTemplate: "{technology} Career Guide: Roles, Skills, Salary, Growth | Glintr",
    descriptionTemplate:
      "A structured career guide for {technology} — role ladder, in-demand skills, salary bands, career paths and how to break in.",
    slugTemplate: "{technology}-career-guide",
    h1Template: "{technology} Career Guide",
    keywords: ["{technology} career", "{technology} jobs", "{technology} career path"],
    sectionPlan: [
      { heading: "Overview of {technology} careers", body: "{technology} careers span product, research, consulting and enterprise settings. The role ladder is broadly consistent across industries." },
      { heading: "Common roles", body: "Roles differ by focus and seniority.", bullets: ["Analyst / Associate roles for early careers", "Engineer / Specialist roles for applied practitioners", "Lead / Architect roles for senior technical direction", "Manager / Director roles for people leadership"] },
      { heading: "Core skills that employers evaluate", body: "Beyond {technology} fundamentals, employers weigh problem-solving, communication and evidence of shipped work through portfolios and case studies." },
      { heading: "How to break into {technology}", body: "Combine structured learning, hands-on projects and interview preparation. Public writing and community involvement accelerate opportunities." },
      { heading: "Long-term career growth", body: "Compounding growth in {technology} comes from picking a strong first role, shipping visibly and choosing the next role for skill overlap rather than only for title." },
    ],
    faqPlan: [
      { q: "What qualifications do I need for a {technology} career?", a: "Most {technology} roles weigh proven skills over specific degrees. A structured program plus a strong project portfolio is usually enough." },
      { q: "Is {technology} a good career choice?", a: "{technology} continues to see strong demand across industries, with clear progression paths and healthy compensation for skilled practitioners." },
    ],
  },
  {
    id: "salary-guide",
    label: "{Technology} Salary Guide",
    pageType: "salary-guide",
    description: "Salary guide with experience bands and drivers.",
    variables: [
      { key: "technology", label: "Technology / Role", required: true },
      { key: "region", label: "Region", placeholder: "India" },
    ],
    titleTemplate: "{technology} Salary Guide in {region}: Ranges, Levels, Skills | Glintr",
    descriptionTemplate:
      "A structured {technology} salary guide for {region} — general ranges by experience, key factors that shift compensation, and skills that raise earnings.",
    slugTemplate: "{technology}-salary-guide",
    h1Template: "{technology} Salary Guide ({region})",
    keywords: ["{technology} salary", "{technology} pay {region}", "{technology} compensation"],
    sectionPlan: [
      { heading: "How this guide is structured", body: "Compensation for {technology} roles in {region} varies with city, employer type and skill depth. This guide describes general patterns rather than specific offers, so treat all figures as directional." },
      { heading: "Experience bands", body: "Compensation typically moves through recognisable levels.", bullets: ["Entry: first 0–2 years, foundation-heavy", "Mid: 2–5 years, applied specialisation", "Senior: 5–10 years, ownership of scope", "Staff / Principal: 10+ years, strategic depth"] },
      { heading: "Key factors that affect {technology} salary", body: "Location, employer type (product vs services vs enterprise), evidence of shipped work, interview performance and negotiation all shift outcomes materially." },
      { heading: "Skills that raise earnings", body: "Specialised skills that pair with {technology} — systems design, domain knowledge, communication and leadership — consistently correlate with above-median compensation." },
      { heading: "How to think about offers", body: "Compare total compensation, growth trajectory and learning environment. A slightly lower base at a stronger team often outperforms a higher base at a stagnant one." },
    ],
    faqPlan: [
      { q: "How much do {technology} professionals earn in {region}?", a: "Compensation for {technology} roles in {region} varies with city, employer and experience. Use this guide as a directional reference and validate with recent offers in your target segment." },
      { q: "What is the highest-paying {technology} role?", a: "Senior specialist and architect roles typically top the {technology} compensation range, especially when combined with rare skills or domain expertise." },
    ],
  },
  {
    id: "technology-roadmap",
    label: "{Technology} Roadmap",
    pageType: "learning-path",
    description: "Step-by-step roadmap for a technology.",
    variables: [{ key: "technology", label: "Technology", required: true }],
    titleTemplate: "{technology} Roadmap {year}: Learn Step by Step | Glintr",
    descriptionTemplate: "A step-by-step {technology} roadmap — prerequisites, phases, projects and interview readiness. Curated by Glintr mentors.",
    slugTemplate: "{technology}-roadmap",
    h1Template: "{technology} Roadmap",
    keywords: ["{technology} roadmap", "learn {technology} step by step", "{technology} path"],
    sectionPlan: [
      { heading: "Roadmap at a glance", body: "This roadmap moves from fundamentals to applied mastery in {technology}. Each phase compounds on the previous one." },
      { heading: "Phase 1 — Foundations", body: "Understand the vocabulary and mental model of {technology}. Reproduce three canonical examples end to end." },
      { heading: "Phase 2 — Applied practice", body: "Move into real-world projects with production-shaped constraints. Prioritise reliability and measurable outcomes." },
      { heading: "Phase 3 — Depth and specialisation", body: "Pick a focus area within {technology} and go deep. Read primary sources and reproduce published work." },
      { heading: "Phase 4 — Career readiness", body: "Convert learning into offers with portfolio, public writing and interview loops." },
    ],
    faqPlan: [
      { q: "How long does the {technology} roadmap take?", a: "Serious learners typically complete this {technology} roadmap in 4–8 months with 8–12 focused hours per week." },
      { q: "Do I need to complete every phase?", a: "The phases build on each other — skipping foundations usually causes learners to stall later. Complete each phase before moving on." },
    ],
  },
  {
    id: "interview-questions",
    label: "{Technology} Interview Questions",
    pageType: "interview-guide",
    description: "Curated interview question sets with prep tips.",
    variables: [{ key: "technology", label: "Technology / Role", required: true }],
    titleTemplate: "{technology} Interview Questions: Beginner to Advanced | Glintr",
    descriptionTemplate: "Prepare for {technology} interviews with a curated question set, answer frameworks and evaluation criteria from Glintr mentors.",
    slugTemplate: "{technology}-interview-questions",
    h1Template: "{technology} Interview Questions",
    keywords: ["{technology} interview questions", "{technology} interview prep", "{technology} interview guide"],
    sectionPlan: [
      { heading: "How {technology} interviews are structured", body: "Most {technology} interviews combine conceptual questions, applied problem solving and behavioural signal. Prepare for all three." },
      { heading: "Fundamentals questions", body: "Interviewers test whether candidates can explain core {technology} ideas in plain language, without buzzwords." },
      { heading: "Applied and case-style questions", body: "Expect open-ended scenarios that ask you to design, debug or improve a real {technology} system. Structure your answer aloud." },
      { heading: "Behavioural questions", body: "Prepare 4–6 stories that show ownership, learning under pressure and collaboration. Use a consistent structure such as situation, action, outcome." },
      { heading: "Preparation plan", body: "Combine one hour of daily {technology} practice with weekly mock interviews. Track weak areas explicitly." },
    ],
    faqPlan: [
      { q: "How should I prepare for {technology} interviews?", a: "Combine fundamentals review, applied practice, and mock interviews. Rotate weak areas into your daily practice." },
      { q: "How many rounds are typical for {technology} interviews?", a: "Companies usually run 3–5 rounds for {technology} roles, mixing technical, applied and behavioural signal." },
    ],
  },
  {
    id: "certification-guide",
    label: "{Technology} Certification Guide",
    pageType: "certification-guide",
    description: "Certification landscape overview.",
    variables: [{ key: "technology", label: "Technology", required: true }],
    titleTemplate: "{technology} Certification Guide: Which One to Pick | Glintr",
    descriptionTemplate: "A neutral guide to {technology} certifications — which certifications actually help, how to choose, and how to prepare efficiently.",
    slugTemplate: "{technology}-certification-guide",
    h1Template: "{technology} Certification Guide",
    keywords: ["{technology} certification", "{technology} certificate", "best {technology} certification"],
    sectionPlan: [
      { heading: "Do {technology} certifications matter?", body: "Certifications matter most when paired with strong projects and interview readiness. Alone, they rarely open doors." },
      { heading: "Types of {technology} certifications", body: "Certifications broadly fall into vendor, association and independent categories.", bullets: ["Vendor certifications validate tool-specific skills", "Association certifications validate broad frameworks", "Independent programs validate applied practice"] },
      { heading: "How to choose a {technology} certification", body: "Match the certification to your target role, not to a generic hiring signal. Read job postings for the role you want and pick the certification most mentioned." },
      { heading: "How to prepare", body: "Combine official study materials, hands-on practice and mock exams. Time-box preparation to 6–10 weeks." },
      { heading: "After certification", body: "Publish a case study demonstrating what you learned. Turn the certification into shipped work." },
    ],
    faqPlan: [
      { q: "Are {technology} certifications worth it?", a: "Certifications are worth it when they match your target role and are paired with real projects. On their own they are rarely decisive." },
      { q: "Which {technology} certification should I take first?", a: "Start with the certification most mentioned in postings for your target role. Avoid stacking certifications without shipping work." },
    ],
  },
  {
    id: "technology-projects",
    label: "{Technology} Projects",
    pageType: "technology-guide",
    description: "Project ideas with difficulty tiers.",
    variables: [{ key: "technology", label: "Technology", required: true }],
    titleTemplate: "{technology} Projects: Beginner to Advanced Ideas | Glintr",
    descriptionTemplate: "Portfolio-ready {technology} project ideas across beginner, intermediate and advanced tiers — with scope, tools and evaluation tips.",
    slugTemplate: "{technology}-projects",
    h1Template: "{technology} Projects",
    keywords: ["{technology} projects", "{technology} project ideas", "{technology} portfolio"],
    sectionPlan: [
      { heading: "What makes a strong {technology} project", body: "A strong {technology} project solves a real problem, uses realistic data or constraints, and ships to a public URL or repository with a clear README." },
      { heading: "Beginner projects", body: "Ideal for learners in the first 1–2 months.", bullets: ["Reproduce a canonical worked example", "Ship a small tool that solves a personal problem", "Analyse a public dataset and publish findings"] },
      { heading: "Intermediate projects", body: "Ideal after fundamentals are solid.", bullets: ["Rebuild a well-known product feature", "Contribute a meaningful patch to an open-source {technology} library", "Ship a product used by real early users"] },
      { heading: "Advanced projects", body: "Ideal for portfolio capstones and senior interviews.", bullets: ["Design and ship a system with production constraints", "Publish a case study covering trade-offs and results", "Present the work publicly (talk, article or demo)"] },
      { heading: "How to present {technology} projects in interviews", body: "Lead with the problem and the outcome. Explain trade-offs and what you would change on a rebuild." },
    ],
    faqPlan: [
      { q: "How many {technology} projects should I have?", a: "Three strong {technology} projects usually outperform ten shallow ones. Depth and clarity matter more than count." },
      { q: "Do side projects count for {technology} interviews?", a: "Yes — a well-documented side project is often stronger interview signal than coursework alone." },
    ],
  },
  {
    id: "technology-for-beginners",
    label: "{Technology} for Beginners",
    pageType: "technology-guide",
    description: "Beginner-focused introduction and starter path.",
    variables: [{ key: "technology", label: "Technology", required: true }],
    titleTemplate: "{technology} for Beginners: A Simple Starter Guide | Glintr",
    descriptionTemplate: "A beginner-friendly guide to {technology} — what it is, why it matters, and a starter path that avoids common mistakes.",
    slugTemplate: "{technology}-for-beginners",
    h1Template: "{technology} for Beginners",
    keywords: ["{technology} for beginners", "learn {technology} from scratch", "{technology} basics"],
    sectionPlan: [
      { heading: "Why {technology} matters", body: "Understanding {technology} at a beginner level helps you evaluate careers, tools and courses more clearly. Even a few weeks of focused learning shifts the mental model." },
      { heading: "Core ideas in {technology}", body: "A handful of core ideas power most of {technology}. Understanding them well is more useful than skimming the entire landscape." },
      { heading: "A starter path for the first 30 days", body: "Structured effort beats scattered tutorials.", bullets: ["Week 1: Vocabulary and mental model", "Week 2: First hands-on exercise", "Week 3: Reproduce a small canonical example", "Week 4: Ship a starter project"] },
      { heading: "Mistakes to avoid", body: "Beginners commonly hop between tutorials, skip fundamentals or copy projects without understanding them. Guard against all three." },
      { heading: "What to do next", body: "After 30 days, move to a structured roadmap and start building a small portfolio." },
    ],
    faqPlan: [
      { q: "Can I learn {technology} on my own?", a: "Yes — many learners self-teach {technology} successfully. A structured path plus mentor feedback shortens the timeline meaningfully." },
      { q: "How long before I can build with {technology}?", a: "Most beginners ship their first small {technology} project within 4–6 weeks of focused practice." },
    ],
  },
  {
    id: "technology-trends",
    label: "{Technology} Trends",
    pageType: "technology-guide",
    description: "State-of-the-industry style trend page.",
    variables: [
      { key: "technology", label: "Technology", required: true },
      { key: "year", label: "Year", placeholder: "2026" },
    ],
    titleTemplate: "{technology} Trends in {year}: What Actually Matters | Glintr",
    descriptionTemplate: "A clear look at {technology} trends in {year} — what changed, what matters and what to ignore. Written for practitioners.",
    slugTemplate: "{technology}-trends-{year}",
    h1Template: "{technology} Trends in {year}",
    keywords: ["{technology} trends", "{technology} {year}", "future of {technology}"],
    sectionPlan: [
      { heading: "What actually shifted this year", body: "Not every headline reflects a real shift. This section separates durable changes in {technology} from short-lived hype." },
      { heading: "Where practitioners are focusing", body: "Working teams have moved attention toward a small set of practical concerns in {technology}." },
      { heading: "What is over-hyped", body: "A few themes attract disproportionate coverage without material impact for most practitioners. Recognising them saves months of misdirected effort." },
      { heading: "What to learn if you have limited time", body: "If you can only invest a few hours per week, focus on the ideas that will still matter in two years." },
      { heading: "Signals to watch", body: "Track a small set of leading indicators — hiring patterns, tooling adoption, canonical publications — instead of daily news." },
    ],
    faqPlan: [
      { q: "Is {technology} still worth learning in {year}?", a: "Yes — {technology} continues to see strong demand, especially for practitioners with applied depth and clear portfolios." },
      { q: "What is the most important {technology} skill in {year}?", a: "Applied problem-solving with modern tooling consistently outperforms narrow specialisation in a single vendor stack." },
    ],
  },
  {
    id: "location-course",
    label: "{Skill} Course in {City}",
    pageType: "location",
    description: "Location-aware course landing page with local usefulness.",
    variables: [
      { key: "skill", label: "Skill", required: true },
      { key: "city", label: "City", required: true },
    ],
    titleTemplate: "{skill} Course in {city}: Curriculum, Fees, Placements | Glintr",
    descriptionTemplate:
      "Learn {skill} in {city} with Glintr — mentor-led curriculum, real projects, placement support and flexible timings for {city} learners.",
    slugTemplate: "{skill}-course-in-{city}",
    h1Template: "{skill} Course in {city}",
    keywords: ["{skill} course in {city}", "{skill} training {city}", "best {skill} institute {city}"],
    sectionPlan: [
      { heading: "Why learn {skill} in {city}", body: "{city} has an active {skill} ecosystem across product companies, services firms and startups. Learning locally shortens the path from training to interviews." },
      { heading: "Curriculum for {city} learners", body: "The Glintr {skill} program in {city} covers fundamentals, applied projects and interview readiness, with schedules designed for {city} working hours." },
      { heading: "Career support in {city}", body: "Placement support focuses on employers hiring {skill} talent in {city}, with mock interviews aligned to local hiring loops." },
      { heading: "Who this is for", body: "Suited to {city}-based students, graduates, working professionals and freelancers who want structured {skill} training with local career support." },
      { heading: "How to enrol", body: "Enrolment happens through Glintr with a short qualification call. Cohorts are limited to keep mentor access strong." },
    ],
    faqPlan: [
      { q: "Is there a good {skill} course in {city}?", a: "Yes — Glintr offers a mentor-led {skill} program with curriculum, projects and placement support designed for {city} learners." },
      { q: "How long is the {skill} course in {city}?", a: "The core {skill} track runs a few months, with extended options for portfolio and interview preparation." },
    ],
  },
  {
    id: "comparison",
    label: "{A} vs {B}",
    pageType: "comparison",
    description: "Head-to-head comparison page.",
    variables: [
      { key: "a", label: "Option A", required: true },
      { key: "b", label: "Option B", required: true },
    ],
    titleTemplate: "{a} vs {b}: Differences, Use Cases, Careers | Glintr",
    descriptionTemplate:
      "A structured comparison of {a} vs {b} — similarities, differences, use cases, pros and cons, career opportunities and how to choose.",
    slugTemplate: "{a}-vs-{b}",
    h1Template: "{a} vs {b}",
    keywords: ["{a} vs {b}", "{a} or {b}", "difference between {a} and {b}"],
    sectionPlan: [
      { heading: "Overview", body: "Both {a} and {b} solve related problems, which is why they are frequently compared. This guide highlights the practical differences that matter." },
      { heading: "Similarities", body: "{a} and {b} share more than most comparisons acknowledge — including audience overlap, adjacent tooling and career pathways." },
      { heading: "Differences", body: "The practical differences show up in scope, tooling depth and typical use cases." },
      { heading: "Use cases", body: "Certain problems fit {a} more naturally; others fit {b}. Choosing well starts with the problem you want to solve." },
      { heading: "Pros and cons", body: "Each option has clear strengths and clear trade-offs — do not treat one as universally better." },
      { heading: "Career opportunities", body: "Careers in {a} and {b} overlap heavily. Skills usually transfer, though depth in one accelerates roles focused on that stack." },
      { heading: "How to choose", body: "Match the option to your goals, target role and existing skills — not to online popularity." },
    ],
    faqPlan: [
      { q: "Is {a} better than {b}?", a: "Neither is universally better — {a} and {b} suit different problems and career paths. Choose based on your goals and target role." },
      { q: "Can I learn both {a} and {b}?", a: "Yes — many practitioners learn {a} first and layer {b} once fundamentals are strong." },
    ],
  },
  {
    id: "how-to-become",
    label: "How to Become a {Role}",
    pageType: "career-guide",
    description: "Career page for a specific target role.",
    variables: [{ key: "role", label: "Role", placeholder: "AI Engineer", required: true }],
    titleTemplate: "How to Become a {role}: Skills, Path, Salary | Glintr",
    descriptionTemplate:
      "A complete guide to becoming a {role} — role overview, skills, learning path, tools, industries, salary and interview preparation.",
    slugTemplate: "how-to-become-a-{role}",
    h1Template: "How to Become a {role}",
    keywords: ["how to become a {role}", "{role} career path", "{role} skills"],
    sectionPlan: [
      { heading: "Role overview", body: "A {role} owns a specific set of problems inside modern teams. This section explains the day-to-day work and the surface area of ownership." },
      { heading: "Skills employers evaluate", body: "Beyond fundamentals, hiring teams weigh applied problem solving, communication and evidence of shipped work.", bullets: ["Core technical fundamentals", "Applied projects with real constraints", "Communication and written clarity", "Understanding of adjacent systems"] },
      { heading: "Learning path", body: "The fastest path to a {role} role blends structured learning, hands-on projects and interview loops. Avoid tutorial-only routes." },
      { heading: "Salary and growth", body: "Compensation for a {role} moves through recognisable levels — early, mid, senior and staff. Growth compounds through visible ownership." },
      { heading: "Tools you should know", body: "The {role} toolkit includes a small set of core tools plus adjacent systems that vary by industry." },
      { heading: "Industries hiring {role}s", body: "Employers span product, services, enterprise and startup segments. Each has a slightly different hiring bar." },
      { heading: "Interview preparation", body: "Combine fundamentals review, applied case practice and behavioural stories. Mock interviews weekly beat solo study." },
    ],
    faqPlan: [
      { q: "How long does it take to become a {role}?", a: "Most focused learners reach entry-level {role} roles in 6–12 months with a strong project portfolio." },
      { q: "Do I need a degree to become a {role}?", a: "Many {role} employers weigh skills and shipped work over specific degrees. A structured program plus portfolio is usually enough." },
    ],
  },
  {
    id: "faq-hub",
    label: "FAQ Hub — {Topic}",
    pageType: "faq",
    description: "Searchable FAQ landing page for a topic.",
    variables: [{ key: "topic", label: "Topic", required: true }],
    titleTemplate: "{topic} FAQs: Answers to Common Questions | Glintr",
    descriptionTemplate: "Answers to the most common {topic} questions — for beginners, learners and professionals. Curated by Glintr mentors.",
    slugTemplate: "{topic}-faqs",
    h1Template: "{topic} — Frequently Asked Questions",
    keywords: ["{topic} FAQ", "{topic} questions", "{topic} basics"],
    sectionPlan: [
      { heading: "About this FAQ", body: "This page collects the questions Glintr mentors hear most often about {topic}. Answers are written for clarity, not hype." },
      { heading: "Getting started", body: "The first questions most learners ask when approaching {topic} — how to begin, how much time to plan for, and where to focus." },
      { heading: "Depth and specialisation", body: "Questions from learners who are past the basics and evaluating where to specialise in {topic}." },
      { heading: "Career and outcomes", body: "Questions about roles, growth and salary related to {topic}." },
    ],
    faqPlan: [
      { q: "Can beginners learn {topic}?", a: "Yes — beginners can learn {topic} with a structured path and consistent weekly effort. Prior technical background helps but is not required." },
      { q: "Is {topic} difficult?", a: "{topic} rewards focused effort. Most learners find the fundamentals approachable when studied in the right order." },
      { q: "How long does it take to learn {topic}?", a: "Serious learners reach applied competence in {topic} within 4–8 months with 8–12 focused hours per week." },
      { q: "Should I learn Python first for {topic}?", a: "Python is a useful default when {topic} involves scripting, but the right first language depends on your target role and stack." },
    ],
  },
  {
    id: "glossary-term",
    label: "Glossary — {Term}",
    pageType: "glossary",
    description: "Definition page for a glossary term.",
    variables: [{ key: "term", label: "Term", required: true }],
    titleTemplate: "{term}: Definition, Meaning, and Examples | Glintr Glossary",
    descriptionTemplate: "A clear definition of {term} — what it means, where it is used and why it matters. Part of the Glintr glossary.",
    slugTemplate: "{term}",
    h1Template: "{term}",
    keywords: ["{term} definition", "{term} meaning", "what is {term}"],
    sectionPlan: [
      { heading: "Definition", body: "{term} refers to a specific concept in its field. This entry explains the meaning in plain language, without buzzwords." },
      { heading: "Where {term} is used", body: "{term} appears across common workflows and adjacent tools. Understanding its role clarifies related concepts too." },
      { heading: "Related concepts", body: "A handful of concepts sit adjacent to {term} and are worth studying together for a stronger mental model." },
      { heading: "Common misconceptions about {term}", body: "Two or three misconceptions cause most confusion around {term}. Recognising them early saves time later." },
    ],
    faqPlan: [
      { q: "What does {term} mean?", a: "{term} refers to a specific concept in its field, with a clear definition and typical usage. See the definition section above for a plain-language explanation." },
      { q: "Where is {term} used?", a: "{term} is used across common workflows in its field and appears in adjacent tools and roles." },
    ],
  },
];

export function getTemplate(id: string) {
  return PSEO_TEMPLATES.find((t) => t.id === id);
}
