import { createFileRoute, Link } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import {
  FileText, Image as ImageIcon, LayoutGrid, Mail, Megaphone,
  Sparkles, CheckSquare, CalendarDays,
} from "lucide-react";

export const Route = createFileRoute("/_authenticated/admin/marketing-os/content")({
  head: () => ({
    meta: [
      { title: "Content — Marketing OS" },
      { name: "description", content: "All AI-generated marketing content in one place." },
    ],
  }),
  component: ContentHub,
});

// Additive restore: the sidebar Content link previously 404'd because no route
// file existed. This hub reuses existing Marketing OS surfaces — nothing new.
const SHORTCUTS: Array<{
  to: string;
  label: string;
  description: string;
  icon: typeof FileText;
}> = [
  {
    to: "/admin/marketing-os/approvals",
    label: "Approval Center",
    description: "Review, edit, and approve every AI-generated post, poster, email, blog, and landing page.",
    icon: CheckSquare,
  },
  {
    to: "/admin/marketing-os/campaigns",
    label: "Campaigns",
    description: "Every campaign and the content generated inside it.",
    icon: Megaphone,
  },
  {
    to: "/admin/marketing-os/planner",
    label: "AI Planner",
    description: "Generate a fresh multi-platform content plan.",
    icon: Sparkles,
  },
  {
    to: "/admin/marketing-os/email",
    label: "Email Marketing",
    description: "AI-drafted email sequences and broadcasts.",
    icon: Mail,
  },
  {
    to: "/admin/marketing-os/media-library",
    label: "Media Library",
    description: "Generated posters, uploaded images, and reusable assets.",
    icon: ImageIcon,
  },
  {
    to: "/admin/marketing-os/publisher",
    label: "Publisher",
    description: "Enqueue approved content to connected social accounts.",
    icon: LayoutGrid,
  },
  {
    to: "/admin/marketing-os/calendar",
    label: "Calendar",
    description: "See what's scheduled across every platform.",
    icon: CalendarDays,
  },
];

function ContentHub() {
  return (
    <div className="space-y-6 max-w-6xl">
      <div>
        <h2 className="text-2xl font-semibold tracking-tight">Content</h2>
        <p className="text-sm text-muted-foreground">
          Jump into any content surface. Posts, posters, emails, blogs, and landing pages generated by AI live in the Approval Center.
        </p>
      </div>

      <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
        {SHORTCUTS.map((s) => {
          const Icon = s.icon;
          return (
            <Link
              key={s.to}
              to={s.to as unknown as "/admin/marketing-os"}
              className="group"
            >
              <Card className="p-4 h-full transition-colors group-hover:border-primary/40 group-hover:bg-primary/5">
                <div className="flex items-start gap-3">
                  <div className="size-9 rounded-lg bg-primary/10 text-primary grid place-items-center shrink-0">
                    <Icon className="size-4" />
                  </div>
                  <div className="min-w-0">
                    <div className="font-medium text-sm">{s.label}</div>
                    <div className="text-xs text-muted-foreground mt-0.5">{s.description}</div>
                  </div>
                </div>
              </Card>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
