import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  Activity, AlertTriangle, CheckCircle2, ChevronRight, ClipboardCheck, Clock, Command, FileText,
  History, ListChecks, Loader2, Pause, Play, RotateCcw, Rocket, Settings2, ShieldCheck, Sparkles,
  Users, Wand2, Workflow, XCircle, Zap,
} from "lucide-react";
import {
  APPROVER_ROLES, EXECUTION_MODES, QA_CHECKS, WORKFLOWS,
  type ApproverRole, type ExecutionMode, type Workflow,
} from "@/lib/execution-engine/catalog";
import {
  useAudit, useExecutionSettings, useRuns,
  type RunRecord, type RunStatus, type StepInstance,
} from "@/lib/execution-engine/storage";

export const Route = createFileRoute("/_authenticated/admin/execution")({
  component: ExecutionCenter,
});

type Tab = "overview" | "workflows" | "runs" | "approvals" | "audit" | "settings";

const TABS: { id: Tab; label: string; icon: any }[] = [
  { id: "overview", label: "Overview", icon: Activity },
  { id: "workflows", label: "Workflow Library", icon: Workflow },
  { id: "runs", label: "Runs", icon: Play },
  { id: "approvals", label: "Approvals", icon: ClipboardCheck },
  { id: "audit", label: "Audit", icon: History },
  { id: "settings", label: "Settings", icon: Settings2 },
];

const STATUS_STYLES: Record<RunStatus, string> = {
  draft: "bg-slate-100 text-slate-700 border-slate-200",
  queued: "bg-amber-50 text-amber-700 border-amber-200",
  running: "bg-blue-50 text-blue-700 border-blue-200",
  paused_for_approval: "bg-purple-50 text-purple-700 border-purple-200",
  review: "bg-cyan-50 text-cyan-700 border-cyan-200",
  published: "bg-emerald-50 text-emerald-700 border-emerald-200",
  failed: "bg-rose-50 text-rose-700 border-rose-200",
  rolled_back: "bg-neutral-100 text-neutral-700 border-neutral-200",
};

function statusLabel(s: RunStatus) {
  return s.replace(/_/g, " ");
}

function ExecutionCenter() {
  const [tab, setTab] = useState<Tab>("overview");
  const [selectedWorkflowId, setSelectedWorkflowId] = useState<string | null>(null);
  const [command, setCommand] = useState("");

  const { settings, update, setWorkflowMode } = useExecutionSettings();
  const { items: runs, start, patchRun, patchStep, rollback, remove } = useRuns();
  const { items: audit, push: pushAudit } = useAudit();

  const stats = useMemo(() => {
    const executed = runs.reduce((n, r) => n + r.steps.filter((s) => s.status === "done").length, 0);
    const hours = runs.reduce((n, r) => n + (r.status === "published" ? r.metrics.hoursSaved : Math.round(r.metrics.hoursSaved * 0.4)), 0);
    const content = runs.reduce((n, r) => n + r.steps.filter((s) => s.status === "done" && /content|blog|email|social|caption/i.test(s.title)).length, 0);
    const campaigns = runs.filter((r) => r.status === "published").length;
    const seo = runs.reduce((n, r) => n + r.steps.filter((s) => s.status === "done" && /seo|schema|indexing/i.test(s.title)).length, 0);
    return { executed, hours, content, campaigns, seo };
  }, [runs]);

  const pendingApprovals = useMemo(() =>
    runs.flatMap((r) => r.steps
      .filter((s) => s.status === "waiting_approval")
      .map((s) => ({ run: r, step: s })))
  , [runs]);

  function launchWorkflow(workflow: Workflow, mode?: ExecutionMode, cmd?: string) {
    const effective = mode ?? settings.perWorkflowMode[workflow.id] ?? workflow.defaultMode;
    const run = start(workflow.id, effective, cmd);
    if (run) {
      pushAudit({ runId: run.id, workflowName: workflow.name, actor: "GlintrAI", action: "run.started", detail: `mode: ${effective}` });
      simulateRun(run.id);
    }
  }

  function simulateRun(runId: string) {
    // Progressive step execution — one tick per second.
    const tick = (index: number) => {
      const current = (JSON.parse(localStorage.getItem("glintr.execution.runs.v1") || "[]") as RunRecord[]).find((r) => r.id === runId);
      if (!current || current.status === "rolled_back" || current.status === "failed") return;
      const step = current.steps[index];
      if (!step) {
        patchRun(runId, { status: "published" });
        pushAudit({ runId, workflowName: current.workflowName, actor: "GlintrAI", action: "run.published" });
        return;
      }
      if (step.requiresApproval && current.mode !== "auto") {
        patchStep(runId, step.id, { status: "waiting_approval", startedAt: Date.now() });
        patchRun(runId, { status: "paused_for_approval" });
        pushAudit({ runId, workflowName: current.workflowName, actor: "GlintrAI", action: "step.paused", detail: step.title });
        return;
      }
      patchStep(runId, step.id, { status: "running", startedAt: Date.now() });
      setTimeout(() => {
        patchStep(runId, step.id, {
          status: "done",
          completedAt: Date.now(),
          output: `${step.produces} generated by ${step.agent}.`,
        });
        pushAudit({ runId, workflowName: current.workflowName, actor: step.agent, action: "step.completed", detail: step.title });
        tick(index + 1);
      }, 700);
    };
    tick(0);
  }

  function approveStep(runId: string, stepId: string) {
    const run = runs.find((r) => r.id === runId); if (!run) return;
    patchStep(runId, stepId, { status: "done", completedAt: Date.now(), approvedBy: "Admin", approvedAt: Date.now(), output: "Approved and executed." });
    patchRun(runId, { status: "running" });
    pushAudit({ runId, workflowName: run.workflowName, actor: "Admin", action: "step.approved" });
    const nextIndex = run.steps.findIndex((s) => s.id === stepId) + 1;
    setTimeout(() => simulateFrom(runId, nextIndex), 400);
  }

  function simulateFrom(runId: string, startIndex: number) {
    const tick = (index: number) => {
      const current = (JSON.parse(localStorage.getItem("glintr.execution.runs.v1") || "[]") as RunRecord[]).find((r) => r.id === runId);
      if (!current) return;
      const step = current.steps[index];
      if (!step) { patchRun(runId, { status: "published" }); return; }
      if (step.status === "done") return tick(index + 1);
      if (step.requiresApproval && current.mode !== "auto") {
        patchStep(runId, step.id, { status: "waiting_approval" });
        patchRun(runId, { status: "paused_for_approval" });
        return;
      }
      patchStep(runId, step.id, { status: "running", startedAt: Date.now() });
      setTimeout(() => {
        patchStep(runId, step.id, { status: "done", completedAt: Date.now(), output: `${step.produces} generated by ${step.agent}.` });
        tick(index + 1);
      }, 700);
    };
    tick(startIndex);
  }

  function rejectStep(runId: string, stepId: string, reason: string) {
    patchStep(runId, stepId, { status: "failed", rejectedReason: reason });
    patchRun(runId, { status: "failed" });
    pushAudit({ runId, workflowName: runs.find((r) => r.id === runId)?.workflowName ?? "", actor: "Admin", action: "step.rejected", detail: reason });
  }

  function handleCommand() {
    const q = command.trim().toLowerCase();
    if (!q) return;
    // naive intent match
    const wf =
      /course|program|engineering|ai program/.test(q) ? WORKFLOWS.find((w) => w.id === "launch-course") :
      /blog/.test(q) ? WORKFLOWS.find((w) => w.id === "publish-blog") :
      /webinar/.test(q) ? WORKFLOWS.find((w) => w.id === "launch-webinar") :
      /placement/.test(q) ? WORKFLOWS.find((w) => w.id === "placement-drive") :
      /campaign|marketing|referral|social/.test(q) ? WORKFLOWS.find((w) => w.id === "social-campaign") :
      /seo/.test(q) ? WORKFLOWS.find((w) => w.id === "seo-sprint") :
      WORKFLOWS[0];
    if (wf) { launchWorkflow(wf, undefined, command); setCommand(""); setTab("runs"); }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <header>
        <p className="text-[11px] font-mono uppercase tracking-[0.16em] text-primary flex items-center gap-1.5">
          <Sparkles className="size-3" /> AI Execution Engine
        </p>
        <h1 className="mt-1 text-2xl font-semibold">Execution Center</h1>
        <p className="mt-1 text-sm text-muted-foreground max-w-3xl">
          GlintrAI no longer just generates — it executes. Launch modular workflows across content, marketing, SEO,
          onboarding and product with draft → review → approval → publish → rollback, plus a full audit trail.
        </p>
      </header>

      {/* GlintrAI Command Bar */}
      <div className="rounded-lg border border-primary/20 bg-gradient-to-r from-primary/5 to-transparent p-4">
        <div className="flex items-center gap-2 mb-2">
          <Command className="size-4 text-primary" />
          <p className="text-xs font-semibold uppercase tracking-wide">GlintrAI Command</p>
        </div>
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            value={command}
            onChange={(e) => setCommand(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleCommand()}
            placeholder='Try: "Launch my AI Engineering program" · "Publish five blogs about Data Science" · "Prepare placement season"'
            className="flex-1 rounded-md border border-border/60 bg-white px-3 py-2 text-sm"
          />
          <button
            onClick={handleCommand}
            className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 flex items-center gap-1.5"
          >
            <Wand2 className="size-4" /> Execute
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex flex-wrap gap-1 border-b border-border/60">
        {TABS.map((t) => {
          const Icon = t.icon;
          const active = tab === t.id;
          return (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`flex items-center gap-1.5 px-3 py-2 text-sm border-b-2 transition ${
                active ? "border-primary text-primary font-medium" : "border-transparent text-muted-foreground hover:text-foreground"
              }`}
            >
              <Icon className="size-4" /> {t.label}
              {t.id === "approvals" && pendingApprovals.length > 0 && (
                <span className="ml-1 rounded-full bg-purple-100 px-1.5 text-[10px] font-semibold text-purple-700">
                  {pendingApprovals.length}
                </span>
              )}
            </button>
          );
        })}
      </div>

      {tab === "overview" && (
        <OverviewTab stats={stats} runs={runs} onOpenWorkflows={() => setTab("workflows")} />
      )}

      {tab === "workflows" && (
        <WorkflowsTab
          settings={settings}
          setWorkflowMode={setWorkflowMode}
          selectedId={selectedWorkflowId}
          onSelect={setSelectedWorkflowId}
          onLaunch={launchWorkflow}
        />
      )}

      {tab === "runs" && (
        <RunsTab runs={runs} onRollback={rollback} onRemove={remove} onResumeApproval={() => setTab("approvals")} />
      )}

      {tab === "approvals" && (
        <ApprovalsTab pending={pendingApprovals} onApprove={approveStep} onReject={rejectStep} />
      )}

      {tab === "audit" && <AuditTab audit={audit} />}

      {tab === "settings" && (
        <SettingsTab settings={settings} update={update} />
      )}
    </div>
  );
}

/* ─── Overview ─── */
function OverviewTab({ stats, runs, onOpenWorkflows }: { stats: any; runs: RunRecord[]; onOpenWorkflows: () => void }) {
  const kpis = [
    { label: "Tasks Executed", value: stats.executed, icon: Zap },
    { label: "Hours Saved", value: `${stats.hours}h`, icon: Clock },
    { label: "Content Generated", value: stats.content, icon: FileText },
    { label: "Campaigns Published", value: stats.campaigns, icon: Rocket },
    { label: "SEO Improvements", value: stats.seo, icon: ShieldCheck },
    { label: "Active Workflows", value: WORKFLOWS.length, icon: Workflow },
  ];
  const recent = runs.slice(0, 6);
  return (
    <div className="space-y-6">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
        {kpis.map((k) => {
          const Icon = k.icon;
          return (
            <div key={k.label} className="rounded-lg border border-border/60 bg-white p-4">
              <div className="flex items-center justify-between">
                <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">{k.label}</p>
                <Icon className="size-4 text-muted-foreground" />
              </div>
              <p className="mt-2 text-2xl font-semibold">{k.value}</p>
            </div>
          );
        })}
      </div>

      <div className="rounded-lg border border-border/60 bg-white p-5">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold">Recent runs</h2>
          <button onClick={onOpenWorkflows} className="text-xs text-primary hover:underline">Browse workflows →</button>
        </div>
        {recent.length === 0 ? (
          <p className="text-sm text-muted-foreground">No runs yet. Use the command bar or open the Workflow Library.</p>
        ) : (
          <ul className="divide-y divide-border/60">
            {recent.map((r) => {
              const done = r.steps.filter((s) => s.status === "done").length;
              return (
                <li key={r.id} className="flex items-center justify-between py-2.5">
                  <div className="min-w-0">
                    <p className="text-sm font-medium truncate">{r.workflowName}</p>
                    <p className="text-[11px] text-muted-foreground">
                      {done}/{r.steps.length} steps · {r.mode} · {new Date(r.startedAt).toLocaleString()}
                    </p>
                  </div>
                  <span className={`rounded-full border px-2 py-0.5 text-[11px] font-medium capitalize ${STATUS_STYLES[r.status]}`}>
                    {statusLabel(r.status)}
                  </span>
                </li>
              );
            })}
          </ul>
        )}
      </div>
    </div>
  );
}

/* ─── Workflow Library ─── */
function WorkflowsTab({
  settings, setWorkflowMode, selectedId, onSelect, onLaunch,
}: {
  settings: any;
  setWorkflowMode: (id: string, mode: ExecutionMode) => void;
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  onLaunch: (w: Workflow, mode?: ExecutionMode) => void;
}) {
  const selected = WORKFLOWS.find((w) => w.id === selectedId) ?? null;
  return (
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]">
      <div className="space-y-2">
        {WORKFLOWS.map((w) => {
          const mode: ExecutionMode = settings.perWorkflowMode[w.id] ?? w.defaultMode;
          const active = selectedId === w.id;
          return (
            <button
              key={w.id}
              onClick={() => onSelect(w.id)}
              className={`w-full text-left rounded-lg border p-4 transition ${
                active ? "border-primary bg-primary/5" : "border-border/60 bg-white hover:border-primary/40"
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="text-sm font-semibold">{w.name}</p>
                  <p className="mt-0.5 text-[12px] text-muted-foreground line-clamp-2">{w.tagline}</p>
                </div>
                <ChevronRight className="size-4 text-muted-foreground shrink-0" />
              </div>
              <div className="mt-2 flex items-center gap-2 text-[11px]">
                <span className="rounded-full bg-primary/10 px-2 py-0.5 text-primary capitalize">{w.category}</span>
                <span className="rounded-full border border-border/60 px-2 py-0.5 capitalize">{EXECUTION_MODES[mode].label}</span>
                <span className="text-muted-foreground">{w.steps.length} steps · ~{w.metrics.hoursSaved}h saved</span>
              </div>
            </button>
          );
        })}
      </div>

      <div className="rounded-lg border border-border/60 bg-white p-5">
        {!selected ? (
          <p className="text-sm text-muted-foreground">Select a workflow to view its steps.</p>
        ) : (
          <>
            <div className="flex flex-wrap items-start justify-between gap-3 mb-4">
              <div>
                <h2 className="text-lg font-semibold">{selected.name}</h2>
                <p className="mt-0.5 text-sm text-muted-foreground max-w-xl">{selected.tagline}</p>
              </div>
              <button
                onClick={() => onLaunch(selected)}
                className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 flex items-center gap-1.5"
              >
                <Play className="size-4" /> Launch
              </button>
            </div>

            <div className="mb-4">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-1">Execution mode</p>
              <div className="flex flex-wrap gap-1.5">
                {(Object.keys(EXECUTION_MODES) as ExecutionMode[]).map((m) => {
                  const active = (settings.perWorkflowMode[selected.id] ?? selected.defaultMode) === m;
                  return (
                    <button
                      key={m}
                      onClick={() => setWorkflowMode(selected.id, m)}
                      className={`rounded-full border px-3 py-1 text-xs capitalize ${
                        active ? "border-primary bg-primary/10 text-primary" : "border-border/60 hover:border-primary/40"
                      }`}
                    >
                      {EXECUTION_MODES[m].label}
                    </button>
                  );
                })}
              </div>
              <p className="mt-1.5 text-[11px] text-muted-foreground">
                {EXECUTION_MODES[settings.perWorkflowMode[selected.id] ?? selected.defaultMode].description}
              </p>
            </div>

            <div className="mb-2 flex items-center gap-2 text-[11px] text-muted-foreground">
              <ListChecks className="size-3.5" /> {selected.steps.length} steps · Approvers: {selected.approvers.map((a) => APPROVER_ROLES[a]).join(", ")}
            </div>
            <ol className="relative border-l border-border/60 pl-4 space-y-3">
              {selected.steps.map((step, i) => (
                <li key={step.id} className="relative">
                  <span className="absolute -left-[21px] top-1 flex size-5 items-center justify-center rounded-full border border-border/60 bg-white text-[10px] font-semibold">
                    {i + 1}
                  </span>
                  <p className="text-sm font-medium">{step.title}</p>
                  <p className="text-[11px] text-muted-foreground">
                    {step.agent} → <em>{step.produces}</em>
                    {step.requiresApproval && step.approver && (
                      <span className="ml-2 rounded-full bg-purple-100 px-1.5 py-0.5 text-[10px] font-medium text-purple-700">
                        Approval · {APPROVER_ROLES[step.approver]}
                      </span>
                    )}
                  </p>
                </li>
              ))}
            </ol>
          </>
        )}
      </div>
    </div>
  );
}

/* ─── Runs ─── */
function RunsTab({
  runs, onRollback, onRemove,
}: {
  runs: RunRecord[]; onRollback: (id: string) => void; onRemove: (id: string) => void; onResumeApproval: () => void;
}) {
  const [openId, setOpenId] = useState<string | null>(null);
  if (runs.length === 0) {
    return <p className="text-sm text-muted-foreground">No runs yet. Launch a workflow to see live execution.</p>;
  }
  return (
    <div className="space-y-3">
      {runs.map((r) => {
        const done = r.steps.filter((s) => s.status === "done").length;
        const isOpen = openId === r.id;
        return (
          <div key={r.id} className="rounded-lg border border-border/60 bg-white">
            <button
              onClick={() => setOpenId(isOpen ? null : r.id)}
              className="w-full flex items-center justify-between gap-3 p-4 text-left"
            >
              <div className="min-w-0">
                <p className="text-sm font-semibold">{r.workflowName}</p>
                <p className="text-[11px] text-muted-foreground">
                  {done}/{r.steps.length} steps · {r.mode} · started {new Date(r.startedAt).toLocaleString()}
                  {r.command && <> · “{r.command}”</>}
                </p>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                <span className={`rounded-full border px-2 py-0.5 text-[11px] font-medium capitalize ${STATUS_STYLES[r.status]}`}>
                  {statusLabel(r.status)}
                </span>
                <ChevronRight className={`size-4 text-muted-foreground transition ${isOpen ? "rotate-90" : ""}`} />
              </div>
            </button>
            {isOpen && (
              <div className="border-t border-border/60 p-4 space-y-3">
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => onRollback(r.id)}
                    className="rounded-md border border-border/60 px-3 py-1.5 text-xs hover:border-primary/40 flex items-center gap-1.5"
                  >
                    <RotateCcw className="size-3.5" /> Rollback
                  </button>
                  <button
                    onClick={() => onRemove(r.id)}
                    className="rounded-md border border-border/60 px-3 py-1.5 text-xs hover:border-rose-400 hover:text-rose-600 flex items-center gap-1.5"
                  >
                    <XCircle className="size-3.5" /> Remove
                  </button>
                </div>
                <ul className="divide-y divide-border/40">
                  {r.steps.map((s) => (
                    <li key={s.id} className="py-2 flex items-start gap-3">
                      <StepIcon status={s.status} />
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium">{s.title}</p>
                        <p className="text-[11px] text-muted-foreground">
                          {s.agent} → {s.produces}
                          {s.output && <span className="ml-1 text-emerald-700">· {s.output}</span>}
                          {s.rejectedReason && <span className="ml-1 text-rose-600">· {s.rejectedReason}</span>}
                        </p>
                      </div>
                      <span className={`shrink-0 rounded-full border px-2 py-0.5 text-[10px] capitalize ${
                        s.status === "done" ? "border-emerald-200 bg-emerald-50 text-emerald-700"
                        : s.status === "running" ? "border-blue-200 bg-blue-50 text-blue-700"
                        : s.status === "waiting_approval" ? "border-purple-200 bg-purple-50 text-purple-700"
                        : s.status === "failed" ? "border-rose-200 bg-rose-50 text-rose-700"
                        : "border-border/60 bg-slate-50 text-slate-700"
                      }`}>
                        {s.status.replace(/_/g, " ")}
                      </span>
                    </li>
                  ))}
                </ul>
                <div className="rounded-md border border-border/60 bg-slate-50/60 p-3">
                  <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-1.5">AI Self-Check</p>
                  <div className="flex flex-wrap gap-1.5">
                    {QA_CHECKS.map((c) => (
                      <span key={c} className="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[11px] text-emerald-700 flex items-center gap-1">
                        <CheckCircle2 className="size-3" /> {c}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

function StepIcon({ status }: { status: StepInstance["status"] }) {
  if (status === "done") return <CheckCircle2 className="size-4 text-emerald-600 mt-0.5" />;
  if (status === "running") return <Loader2 className="size-4 text-blue-600 mt-0.5 animate-spin" />;
  if (status === "waiting_approval") return <Pause className="size-4 text-purple-600 mt-0.5" />;
  if (status === "failed") return <AlertTriangle className="size-4 text-rose-600 mt-0.5" />;
  if (status === "rolled_back") return <RotateCcw className="size-4 text-neutral-500 mt-0.5" />;
  return <span className="size-4 rounded-full border border-border/60 mt-0.5" />;
}

/* ─── Approvals ─── */
function ApprovalsTab({
  pending, onApprove, onReject,
}: {
  pending: { run: RunRecord; step: StepInstance }[];
  onApprove: (runId: string, stepId: string) => void;
  onReject: (runId: string, stepId: string, reason: string) => void;
}) {
  if (pending.length === 0) {
    return <p className="text-sm text-muted-foreground">No approvals pending. Approvals appear here when workflows pause on gated steps.</p>;
  }
  return (
    <div className="space-y-3">
      {pending.map(({ run, step }) => (
        <div key={step.id} className="rounded-lg border border-purple-200 bg-purple-50/40 p-4">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div className="min-w-0">
              <p className="text-[11px] font-semibold uppercase tracking-wide text-purple-700">
                {step.approver ? APPROVER_ROLES[step.approver] : "Reviewer"} approval
              </p>
              <p className="mt-1 text-sm font-semibold">{step.title}</p>
              <p className="text-[11px] text-muted-foreground">
                {run.workflowName} · {step.agent} → {step.produces}
              </p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => {
                  const reason = window.prompt("Rejection reason?") || "Rejected";
                  onReject(run.id, step.id, reason);
                }}
                className="rounded-md border border-rose-200 px-3 py-1.5 text-xs text-rose-700 hover:bg-rose-50"
              >
                Reject
              </button>
              <button
                onClick={() => onApprove(run.id, step.id)}
                className="rounded-md bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:bg-primary/90"
              >
                Approve & continue
              </button>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

/* ─── Audit ─── */
function AuditTab({ audit }: { audit: ReturnType<typeof useAudit>["items"] }) {
  if (audit.length === 0) return <p className="text-sm text-muted-foreground">No audit entries yet.</p>;
  return (
    <div className="rounded-lg border border-border/60 bg-white">
      <ul className="divide-y divide-border/60">
        {audit.map((a) => (
          <li key={a.id} className="p-3 flex items-start gap-3">
            <span className="mt-0.5 rounded-md bg-slate-100 p-1.5"><History className="size-3.5" /></span>
            <div className="min-w-0 flex-1">
              <p className="text-sm">
                <span className="font-medium">{a.actor}</span>{" "}
                <span className="text-muted-foreground">{a.action}</span>
                {a.detail && <span className="text-muted-foreground"> · {a.detail}</span>}
              </p>
              <p className="text-[11px] text-muted-foreground">{a.workflowName} · {new Date(a.at).toLocaleString()}</p>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

/* ─── Settings ─── */
function SettingsTab({
  settings, update,
}: { settings: any; update: (patch: any) => void }) {
  return (
    <div className="space-y-4 max-w-2xl">
      <div className="rounded-lg border border-border/60 bg-white p-5">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-2">Default execution mode</p>
        <div className="flex flex-wrap gap-1.5">
          {(Object.keys(EXECUTION_MODES) as ExecutionMode[]).map((m) => {
            const active = settings.defaultMode === m;
            return (
              <button
                key={m}
                onClick={() => update({ defaultMode: m })}
                className={`rounded-full border px-3 py-1 text-xs capitalize ${
                  active ? "border-primary bg-primary/10 text-primary" : "border-border/60 hover:border-primary/40"
                }`}
              >
                {EXECUTION_MODES[m].label}
              </button>
            );
          })}
        </div>
        <p className="mt-2 text-[11px] text-muted-foreground">{EXECUTION_MODES[settings.defaultMode as ExecutionMode].description}</p>
      </div>

      <div className="rounded-lg border border-border/60 bg-white p-5">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-2">Active approver roles</p>
        <div className="flex flex-wrap gap-1.5">
          {(Object.keys(APPROVER_ROLES) as ApproverRole[]).map((r) => {
            const active = settings.activeApprovers.includes(r);
            return (
              <button
                key={r}
                onClick={() => {
                  const set = new Set<ApproverRole>(settings.activeApprovers);
                  if (active) set.delete(r); else set.add(r);
                  update({ activeApprovers: Array.from(set) });
                }}
                className={`rounded-full border px-3 py-1 text-xs flex items-center gap-1 ${
                  active ? "border-primary bg-primary/10 text-primary" : "border-border/60 hover:border-primary/40"
                }`}
              >
                <Users className="size-3" /> {APPROVER_ROLES[r]}
              </button>
            );
          })}
        </div>
      </div>

      <div className="rounded-lg border border-border/60 bg-white p-5 space-y-3">
        <label className="flex items-center justify-between text-sm">
          <span>Run AI self-check before publish</span>
          <input
            type="checkbox"
            checked={settings.selfCheckEnabled}
            onChange={(e) => update({ selfCheckEnabled: e.target.checked })}
          />
        </label>
        <label className="flex items-center justify-between text-sm">
          <span>Block publish when a QA check fails</span>
          <input
            type="checkbox"
            checked={settings.qaBlockOnFail}
            onChange={(e) => update({ qaBlockOnFail: e.target.checked })}
          />
        </label>
      </div>
    </div>
  );
}
