import { createFileRoute, Link } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Search, Link2, Braces, ListTree, Sparkles, ShieldCheck } from "lucide-react";

export const Route = createFileRoute("/_authenticated/admin/ai-content/seo")({
  component: SeoPage,
});

const CHECKS = [
  { icon: Sparkles, label: "SEO Title", desc: "Under 60 characters, includes primary keyword, brand suffix." },
  { icon: Sparkles, label: "Meta Description", desc: "140–160 characters with a clear benefit and CTA." },
  { icon: Link2, label: "Canonical URL", desc: "Self-referencing canonical set on every leaf route." },
  { icon: Braces, label: "Article Schema", desc: "JSON-LD Article with headline, author, image, dates." },
  { icon: Braces, label: "Breadcrumb Schema", desc: "ItemList breadcrumb from Home → Section → Article." },
  { icon: Braces, label: "FAQ Schema", desc: "FAQPage schema when the article carries an FAQ block." },
  { icon: ListTree, label: "Internal Links", desc: "3+ contextual links to programs, blogs or roadmaps." },
  { icon: Link2, label: "Related Topics", desc: "Related blogs and courses surfaced automatically." },
];

function SeoPage() {
  return (
    <div className="space-y-6 max-w-7xl">
      <header>
        <h1 className="font-display text-2xl font-semibold flex items-center gap-2">
          <Search className="size-5 text-primary" /> SEO
        </h1>
        <p className="text-sm text-muted-foreground">Every article generated by Glintr's AI Content Engine ships with production-grade on-page SEO and structured data.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">
        <Card className="p-4">
          <div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">Avg SEO Score</div>
          <div className="text-3xl font-display font-semibold mt-1">92<span className="text-sm text-muted-foreground">/100</span></div>
        </Card>
        <Card className="p-4">
          <div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">Avg GEO Score</div>
          <div className="text-3xl font-display font-semibold mt-1">88<span className="text-sm text-muted-foreground">/100</span></div>
        </Card>
        <Card className="p-4">
          <div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">Schema Coverage</div>
          <div className="text-3xl font-display font-semibold mt-1">100<span className="text-sm text-muted-foreground">%</span></div>
        </Card>
        <Card className="p-4">
          <div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">Avg Internal Links</div>
          <div className="text-3xl font-display font-semibold mt-1">6.4</div>
        </Card>
      </div>

      <Card className="p-5">
        <h2 className="font-display text-base font-semibold mb-4 flex items-center gap-2">
          <ShieldCheck className="size-4 text-primary" /> On-page SEO checklist (auto-applied)
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {CHECKS.map((c) => {
            const Icon = c.icon;
            return (
              <div key={c.label} className="flex gap-3">
                <div className="size-8 rounded-md bg-primary/10 text-primary flex items-center justify-center shrink-0">
                  <Icon className="size-4" />
                </div>
                <div>
                  <div className="text-sm font-semibold">{c.label}</div>
                  <div className="text-[12px] text-muted-foreground leading-relaxed">{c.desc}</div>
                </div>
              </div>
            );
          })}
        </div>
      </Card>

      <Card className="p-5">
        <h2 className="font-display text-base font-semibold mb-1">Deep SEO tooling</h2>
        <p className="text-sm text-muted-foreground">
          For keyword research, SERP analysis, and cluster planning use the{" "}
          <Link to={"/admin/ai-content/suggestions" as any} className="text-primary hover:underline">AI Suggestions</Link> and{" "}
          <Link to={"/admin/ai-content/clusters" as any} className="text-primary hover:underline">Topic Clusters</Link> workspaces.
        </p>
      </Card>
    </div>
  );
}
