import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { getAiFactoryDashboard } from "@/lib/admin/ai-content.functions";
import { Card } from "@/components/ui/card";
import { Sparkles, CheckCircle2, Clock, Calendar, AlertTriangle, TrendingUp, Link2, BookOpen, Search } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { CONTENT_TYPE_LABEL } from "@/lib/admin/content-meta";

export const Route = createFileRoute("/_authenticated/admin/ai-content/")({
  component: FactoryDashboard,
});

function FactoryDashboard() {
  const fn = useServerFn(getAiFactoryDashboard);
  const { data, isLoading } = useQuery({ queryKey: ["ai-factory-dashboard"], queryFn: () => fn(), staleTime: 30_000 });

  return (
    <div className="space-y-6 max-w-7xl">
      <header className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="font-display text-2xl font-semibold flex items-center gap-2"><Sparkles className="size-5 text-primary" /> AI Content Factory</h1>
          <p className="text-sm text-muted-foreground">Scale editorial output while every article stays reviewed by a human.</p>
        </div>
        <Link to={"/admin/ai-content/wizard" as any} className="inline-flex items-center gap-1.5 rounded-md bg-primary text-primary-foreground px-3 py-2 text-sm font-medium hover:opacity-90">
          <Sparkles className="size-4" /> New AI draft
        </Link>
      </header>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Kpi icon={Sparkles} label="AI Drafts" value={data?.kpis.aiGenerated} loading={isLoading} />
        <Kpi icon={Clock} label="Pending Review" value={data?.kpis.pendingReview} tone="warn" loading={isLoading} />
        <Kpi icon={CheckCircle2} label="Published" value={data?.kpis.published} tone="good" loading={isLoading} />
        <Kpi icon={Calendar} label="Scheduled" value={data?.kpis.scheduled} tone="info" loading={isLoading} />
      </div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Kpi icon={AlertTriangle} label="Needs Improvement" value={data?.kpis.needsImprovement} tone="warn" loading={isLoading} />
        <Kpi icon={Search} label="SEO Score" value={`${data?.kpis.seoScore ?? 0}`} suffix="/100" loading={isLoading} />
        <Kpi icon={Link2} label="Internal Link Score" value={`${data?.kpis.linkScore ?? 0}`} suffix="/100" loading={isLoading} />
        <Kpi icon={BookOpen} label="Avg Reading Time" value={`${data?.kpis.avgReadingTimeMin ?? 0}`} suffix="min" loading={isLoading} />
      </div>

      <Card className="p-5">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-display text-base font-semibold flex items-center gap-2"><TrendingUp className="size-4" /> Overall Quality Score</h2>
          <div className="text-3xl font-display font-semibold">{data?.kpis.qualityScore ?? 0}<span className="text-sm text-muted-foreground">/100</span></div>
        </div>
        <div className="h-2 bg-surface-2 rounded-full overflow-hidden">
          <div className="h-full bg-primary transition-all" style={{ width: `${data?.kpis.qualityScore ?? 0}%` }} />
        </div>
        <p className="text-xs text-muted-foreground mt-2">Average of readability, structure, SEO, internal linking, completeness, accessibility and uniqueness across all published content.</p>
      </Card>

      <Card className="p-5">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-display text-base font-semibold">Recently generated by AI</h2>
          <Link to={"/admin/ai-content/review" as any} className="text-xs text-primary hover:underline">Open review queue →</Link>
        </div>
        <div className="divide-y divide-border/60">
          {(data?.recentAi ?? []).map((r: any) => (
            <Link key={r.id} to={"/admin/content/articles/$id" as any} params={{ id: r.id } as any} className="flex items-center justify-between py-2 hover:bg-surface-2/40 rounded px-2">
              <div className="min-w-0">
                <div className="text-sm font-medium truncate">{r.title}</div>
                <div className="text-[11px] text-muted-foreground">
                  {CONTENT_TYPE_LABEL[r.type]} · {r.word_count ?? 0} words · updated {formatDistanceToNow(new Date(r.updated_at))} ago
                </div>
              </div>
              <span className="inline-flex text-[10px] uppercase font-medium px-2 py-0.5 rounded bg-primary/10 text-primary">{r.status}</span>
            </Link>
          ))}
          {!(data?.recentAi ?? []).length && (
            <div className="text-sm text-muted-foreground text-center py-10">
              No AI drafts yet — start with the <Link to={"/admin/ai-content/wizard" as any} className="text-primary hover:underline">Content Wizard</Link>.
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}

function Kpi({ icon: Icon, label, value, tone, loading, suffix }: any) {
  const toneClass = { good: "text-emerald-600", warn: "text-amber-600", info: "text-primary" }[tone as string] ?? "text-foreground";
  return (
    <Card className="p-4">
      <div className="flex items-center gap-2 text-[11px] uppercase tracking-wide text-muted-foreground">
        <Icon className="size-3.5" /> {label}
      </div>
      <div className={`mt-1.5 text-2xl font-display font-semibold ${toneClass}`}>
        {loading ? "—" : (value ?? 0)}{suffix && <span className="text-sm text-muted-foreground ml-1">{suffix}</span>}
      </div>
    </Card>
  );
}
