import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { GraduationCap, Sparkles, Globe, Palette, BookOpen, Megaphone, Check, ArrowRight, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_authenticated/partner/launch-academy")({
  head: () => ({
    meta: [
      { title: "Launch My Own Academy — Glintr Partner" },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: LaunchAcademyIntro,
});

const OPT_IN_KEY = "glintr.partner.academy.optin";

const BENEFITS = [
  { icon: Palette, title: "Your own brand", copy: "Logo, colors, tone-of-voice, and brand kit — generated by AI." },
  { icon: Globe, title: "Fully managed by Glintr", copy: "Website, hosting, SSL, CDN, backups, SEO — Glintr runs the entire tech stack for your academy." },
  { icon: BookOpen, title: "Your own courses", copy: "AI-authored curriculum, lessons, quizzes, certificates, and student portal." },
  { icon: Megaphone, title: "Marketing, done", copy: "Blogs, social posts, ads, emails, SEO — a marketing team in a box." },
  { icon: Sparkles, title: "AI Employees", copy: "AI Sales Coach, AI Marketing Manager, AI Support — running 24/7." },
  { icon: ShieldCheck, title: "Draft-first publishing", copy: "Everything AI creates stays in draft until you review and publish." },
] as const;

const NOT_FOR_YOU = [
  "You just want to sell existing Glintr programs — stay on Sales Partner (70%).",
  "You want verified leads from Glintr — stay on Assisted Sales (50%).",
  "You're not ready to run an education brand end-to-end.",
];

function LaunchAcademyIntro() {
  const navigate = useNavigate();

  function optInAndGo() {
    try { localStorage.setItem(OPT_IN_KEY, "1"); } catch { /* noop */ }
    navigate({ to: "/partner/academy-builder" });
  }

  return (
    <div className="max-w-5xl mx-auto p-4 sm:p-6 lg:p-10 space-y-10">
      <header className="space-y-4">
        <div className="text-caption font-mono uppercase tracking-widest text-primary">
          Optional Upgrade
        </div>
        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-display font-semibold tracking-tight max-w-3xl">
          Launch your own education brand — powered by AI.
        </h1>
        <p className="text-muted-foreground max-w-2xl text-lg">
          Academy Builder is optional. You keep everything you have as a sales partner.
          When you're ready to run your own brand, Glintr generates the website, courses, blog,
          marketing, and AI employees for you.
        </p>
      </header>

      <section className="rounded-2xl border bg-white p-6 sm:p-8">
        <div className="flex items-start gap-3 mb-6">
          <div className="inline-flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary shrink-0">
            <GraduationCap className="size-5" />
          </div>
          <div>
            <h2 className="font-display text-xl font-semibold tracking-tight">What you unlock</h2>
            <p className="text-sm text-muted-foreground">Everything below stays as draft until you publish.</p>
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {BENEFITS.map((b) => (
            <div key={b.title} className="rounded-xl border p-4 hover:border-primary/40 transition-colors">
              <div className="flex items-center gap-2 mb-1.5">
                <b.icon className="size-4 text-primary" />
                <div className="font-medium">{b.title}</div>
              </div>
              <p className="text-sm text-muted-foreground">{b.copy}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="rounded-2xl border bg-white p-6">
          <div className="text-[10px] font-mono uppercase tracking-widest text-emerald-600">
            You'll get access to
          </div>
          <ul className="mt-3 space-y-2 text-sm">
            {[
              "Brand Name & Logo Generator",
              "Domain Availability Checker + AI suggestions",
              "Website Generator (landing, about, curriculum)",
              "Course & Curriculum Generator",
              "Blog Generator (25 draft articles)",
              "Marketing, SEO, Email & Social Generators",
              "Certificate & Video Generators",
              "AI Chatbot Builder",
            ].map((t) => (
              <li key={t} className="flex items-start gap-2">
                <Check className="size-4 text-emerald-600 shrink-0 mt-0.5" />
                <span>{t}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-2xl border bg-slate-50/60 p-6">
          <div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">
            Skip this if…
          </div>
          <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
            {NOT_FOR_YOU.map((t) => (
              <li key={t} className="flex items-start gap-2">
                <span className="mt-2 size-1 rounded-full bg-muted-foreground/50 shrink-0" />
                <span>{t}</span>
              </li>
            ))}
          </ul>
          <Link
            to="/partner/dashboard"
            className="mt-6 inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
          >
            Stay on my current plan <ArrowRight className="size-3.5" />
          </Link>
        </div>
      </section>

      <div className="rounded-2xl border bg-gradient-to-br from-primary/[0.06] via-white to-emerald-50/40 p-6 sm:p-8 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="font-display text-xl font-semibold tracking-tight">Ready to launch your academy?</div>
          <p className="text-sm text-muted-foreground mt-1">You can undo this anytime from your account settings.</p>
        </div>
        <Button size="lg" onClick={optInAndGo} className="gap-2">
          Launch My Own Academy <ArrowRight className="size-4" />
        </Button>
      </div>
    </div>
  );
}
