/**
 * AI Creative Studio — shared types
 * ---------------------------------
 * Backend-only module. Provides typed shapes for design specs generated by
 * the AI layout engine and consumed by any future renderer / editor.
 */

export type DesignFormat =
  | "instagram_post"
  | "instagram_carousel"
  | "instagram_story"
  | "facebook_post"
  | "facebook_cover"
  | "linkedin_post"
  | "linkedin_carousel"
  | "linkedin_banner"
  | "x_post_image"
  | "youtube_thumbnail"
  | "youtube_banner"
  | "blog_featured"
  | "email_banner"
  | "website_hero"
  | "course_poster"
  | "webinar_poster"
  | "workshop_poster"
  | "event_poster"
  | "internship_promo"
  | "hiring_poster"
  | "certificate"
  | "presentation_cover"
  | "infographic"
  | "quote_card"
  | "flyer"
  | "brochure"
  | "business_card"
  | "social_ad";

export type DesignStyle =
  | "minimal"
  | "modern"
  | "corporate"
  | "startup"
  | "glassmorphism"
  | "neumorphism"
  | "dark"
  | "light"
  | "premium"
  | "bold"
  | "luxury";

export type DesignCategory =
  | "education"
  | "technology"
  | "finance"
  | "healthcare"
  | "events"
  | "hiring"
  | "internships"
  | "certifications"
  | "discount"
  | "admissions"
  | "announcements"
  | "festivals"
  | "ai"
  | "marketing"
  | "business"
  | "corporate";

export interface FormatSpec {
  width: number;
  height: number;
  slides?: number; // for carousels
  label: string;
}

export const FORMAT_SPECS: Record<DesignFormat, FormatSpec> = {
  instagram_post: { width: 1080, height: 1080, label: "Instagram Post" },
  instagram_carousel: { width: 1080, height: 1080, slides: 5, label: "Instagram Carousel" },
  instagram_story: { width: 1080, height: 1920, label: "Instagram Story" },
  facebook_post: { width: 1200, height: 630, label: "Facebook Post" },
  facebook_cover: { width: 1640, height: 924, label: "Facebook Cover" },
  linkedin_post: { width: 1200, height: 1200, label: "LinkedIn Post" },
  linkedin_carousel: { width: 1080, height: 1350, slides: 6, label: "LinkedIn Carousel" },
  linkedin_banner: { width: 1584, height: 396, label: "LinkedIn Banner" },
  x_post_image: { width: 1600, height: 900, label: "X Post Image" },
  youtube_thumbnail: { width: 1280, height: 720, label: "YouTube Thumbnail" },
  youtube_banner: { width: 2560, height: 1440, label: "YouTube Banner" },
  blog_featured: { width: 1600, height: 900, label: "Blog Featured Image" },
  email_banner: { width: 1200, height: 400, label: "Email Banner" },
  website_hero: { width: 1920, height: 1080, label: "Website Hero" },
  course_poster: { width: 1080, height: 1350, label: "Course Poster" },
  webinar_poster: { width: 1080, height: 1350, label: "Webinar Poster" },
  workshop_poster: { width: 1080, height: 1350, label: "Workshop Poster" },
  event_poster: { width: 1080, height: 1350, label: "Event Poster" },
  internship_promo: { width: 1080, height: 1350, label: "Internship Promo" },
  hiring_poster: { width: 1080, height: 1350, label: "Hiring Poster" },
  certificate: { width: 1600, height: 1131, label: "Certificate" },
  presentation_cover: { width: 1920, height: 1080, label: "Presentation Cover" },
  infographic: { width: 1080, height: 1920, label: "Infographic" },
  quote_card: { width: 1080, height: 1080, label: "Quote Card" },
  flyer: { width: 1240, height: 1754, label: "Flyer" },
  brochure: { width: 2480, height: 1754, label: "Brochure" },
  business_card: { width: 1050, height: 600, label: "Business Card" },
  social_ad: { width: 1200, height: 1200, label: "Social Ad" },
};

export interface DesignPalette {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  foreground: string;
  muted?: string;
}

export interface DesignTypography {
  heading: { family: string; weight: number; size: number };
  subheading: { family: string; weight: number; size: number };
  body: { family: string; weight: number; size: number };
  cta: { family: string; weight: number; size: number };
}

export interface DesignCopy {
  headline: string;
  subheadline?: string;
  body?: string;
  cta?: string;
  hashtags?: string[];
  keywords?: string[];
  caption?: string;
  bullets?: string[];
  benefits?: string[];
  footer?: string;
}

export type ElementKind =
  | "text"
  | "image"
  | "icon"
  | "shape"
  | "logo"
  | "cta"
  | "qr"
  | "watermark"
  | "background";

export interface DesignElement {
  id: string;
  kind: ElementKind;
  role?: string; // headline | subheadline | body | cta | ...
  x: number;
  y: number;
  width: number;
  height: number;
  rotation?: number;
  z?: number;
  locked?: boolean;
  grouped?: string;
  content?: string;
  src?: string;
  color?: string;
  bgColor?: string;
  font?: { family: string; weight: number; size: number };
  align?: "left" | "center" | "right";
  radius?: number;
  opacity?: number;
  meta?: Record<string, unknown>;
}

export interface DesignSlide {
  index: number;
  elements: DesignElement[];
  background?: {
    kind: "solid" | "gradient" | "image";
    value: string; // color, gradient css, or image url
  };
}

export interface DesignLayout {
  format: DesignFormat;
  style: DesignStyle;
  canvas: { width: number; height: number };
  slides: DesignSlide[];
  grid?: { rows: number; cols: number };
}

export interface BrandKitSnapshot {
  id: string;
  name: string;
  logoUrl: string | null;
  primary: string;
  secondary: string;
  accent: string;
  headingFont: string;
  bodyFont: string;
  toneOfVoice: string | null;
  ctaStyle: string | null;
  buttonStyle: string | null;
  borderRadius: string | null;
  watermarkUrl: string | null;
}
