import {
  Crown,
  Megaphone,
  Search,
  PenTool,
  Palette,
  Video,
  Target,
  GraduationCap,
  Cog,
  Wallet,
  Users,
  LifeBuoy,
  BarChart3,
  type LucideIcon,
} from "lucide-react";

export type AIEmployee = {
  slug: string;
  name: string;
  role: string;
  icon: LucideIcon;
  tagline: string;
  bio: string;
  skills: string[];
  responsibilities: string[];
  outputs: string[];
  color: string;
};

export const AI_EMPLOYEES: AIEmployee[] = [
  {
    slug: "ai-ceo",
    name: "Aria",
    role: "AI CEO",
    icon: Crown,
    tagline: "Runs your daily business review",
    bio: "Reviews revenue, growth, and priorities across your academy every morning and hands you a briefing.",
    skills: ["Strategy", "Growth", "OKRs", "Revenue Analysis", "Priority Ranking"],
    responsibilities: [
      "Daily Business Report",
      "Growth Suggestions",
      "Revenue Analysis",
      "Performance Review",
      "Weekly & Monthly Goals",
      "Priority Task List",
    ],
    outputs: ["Daily briefing", "Weekly goal sheet", "Monthly performance memo"],
    color: "from-amber-100 to-amber-50 text-amber-900",
  },
  {
    slug: "ai-marketing-manager",
    name: "Mira",
    role: "AI Marketing Manager",
    icon: Megaphone,
    tagline: "Plans and drafts every campaign",
    bio: "Owns the marketing calendar and drafts every campaign across email, social, and paid.",
    skills: ["Content Calendar", "Copywriting", "Email", "Landing Pages", "Paid Ads"],
    responsibilities: [
      "Marketing Calendar",
      "Campaign Ideas",
      "Instagram, LinkedIn, Facebook Posts",
      "YouTube Ideas",
      "Email Campaigns",
      "Landing Pages",
      "Ads",
    ],
    outputs: ["Weekly content calendar", "Campaign briefs", "Ad copy"],
    color: "from-rose-100 to-rose-50 text-rose-900",
  },
  {
    slug: "ai-seo-specialist",
    name: "Sage",
    role: "AI SEO Specialist",
    icon: Search,
    tagline: "Watches rankings, schema, and speed",
    bio: "Continuously audits your academy for indexing, keywords, page speed, and content gaps.",
    skills: ["Technical SEO", "Keyword Research", "Schema", "Internal Linking", "Core Web Vitals"],
    responsibilities: [
      "Keyword Rankings",
      "Technical SEO",
      "Broken Links",
      "Schema",
      "Internal Linking",
      "Page Speed",
      "Blog Performance",
      "Competitor Opportunities",
    ],
    outputs: ["SEO audit", "Keyword opportunities", "Link fixes"],
    color: "from-emerald-100 to-emerald-50 text-emerald-900",
  },
  {
    slug: "ai-content-writer",
    name: "Nova",
    role: "AI Content Writer",
    icon: PenTool,
    tagline: "Drafts blogs, guides, and FAQs",
    bio: "Turns topic briefs into full-length articles, learn guides, glossary entries, and FAQs.",
    skills: ["Long-form", "SEO Writing", "Editorial", "Course Copy"],
    responsibilities: [
      "Blogs",
      "Learn Guides",
      "Career Guides",
      "Glossary",
      "FAQs",
      "Case Studies",
      "Email Campaigns",
      "Course Descriptions",
    ],
    outputs: ["Blog drafts", "Guides", "FAQ pages"],
    color: "from-sky-100 to-sky-50 text-sky-900",
  },
  {
    slug: "ai-graphic-designer",
    name: "Kite",
    role: "AI Graphic Designer",
    icon: Palette,
    tagline: "Produces on-brand visuals",
    bio: "Designs course covers, banners, certificates, and social graphics using your brand kit.",
    skills: ["Brand Kit", "Illustration", "Layouts", "Certificates"],
    responsibilities: [
      "Logos",
      "Course Covers",
      "Program Banners",
      "Blog Images",
      "Social Media Graphics",
      "Certificates",
      "Brochures",
      "Infographics",
    ],
    outputs: ["Course covers", "Social graphics", "Certificate templates"],
    color: "from-violet-100 to-violet-50 text-violet-900",
  },
  {
    slug: "ai-video-creator",
    name: "Reel",
    role: "AI Video Creator",
    icon: Video,
    tagline: "Cuts intros, reels, and shorts",
    bio: "Produces course intro videos, reels, shorts, and voiceovers from your outlines.",
    skills: ["Scripts", "Voiceover", "Reels", "Explainer Animation"],
    responsibilities: [
      "Course Intros",
      "Reels",
      "Shorts",
      "Marketing Videos",
      "Voiceovers",
      "Animated Explainers",
    ],
    outputs: ["Video scripts", "Reels", "Voiceover assets"],
    color: "from-fuchsia-100 to-fuchsia-50 text-fuchsia-900",
  },
  {
    slug: "ai-sales-manager",
    name: "Rex",
    role: "AI Sales Manager",
    icon: Target,
    tagline: "Prioritises leads and follow-ups",
    bio: "Scores leads, drafts follow-ups, and recommends the next best action for every prospect.",
    skills: ["Lead Scoring", "Sales Copy", "Pipeline", "Forecasting"],
    responsibilities: ["Leads", "Follow Ups", "Conversions", "Sales Performance", "Next Actions"],
    outputs: ["Lead priority list", "Follow-up drafts", "Weekly pipeline"],
    color: "from-orange-100 to-orange-50 text-orange-900",
  },
  {
    slug: "ai-student-counselor",
    name: "Iris",
    role: "AI Student Counselor",
    icon: GraduationCap,
    tagline: "Guides every student's path",
    bio: "Recommends courses, answers FAQs, and builds learning paths tailored to each student.",
    skills: ["Guidance", "Learning Paths", "Q&A", "Engagement"],
    responsibilities: ["Course Recommendations", "FAQ Responses", "Learning Paths", "Engagement Monitoring"],
    outputs: ["Learning paths", "FAQ replies", "Engagement flags"],
    color: "from-teal-100 to-teal-50 text-teal-900",
  },
  {
    slug: "ai-operations-manager",
    name: "Ops",
    role: "AI Operations Manager",
    icon: Cog,
    tagline: "Keeps the platform humming",
    bio: "Monitors website, publishing, certificates, and automation across the academy.",
    skills: ["Publishing", "CRM", "Automation", "QA"],
    responsibilities: ["Website", "Courses", "Publishing", "Certificates", "Emails", "CRM", "Automation"],
    outputs: ["Publishing queue", "Ops health report", "Automation logs"],
    color: "from-slate-100 to-slate-50 text-slate-900",
  },
  {
    slug: "ai-finance-manager",
    name: "Vera",
    role: "AI Finance Manager",
    icon: Wallet,
    tagline: "Tracks revenue and payouts",
    bio: "Watches revenue, expenses, refunds, and partner earnings and forecasts the next month.",
    skills: ["Revenue", "Forecasts", "Refunds", "Payouts"],
    responsibilities: ["Revenue", "Expenses", "Partner Earnings", "Refunds", "Forecasts"],
    outputs: ["Monthly P&L", "Cashflow forecast", "Refund summary"],
    color: "from-lime-100 to-lime-50 text-lime-900",
  },
  {
    slug: "ai-hr-manager",
    name: "Hana",
    role: "AI HR Manager",
    icon: Users,
    tagline: "Coordinates your human team",
    bio: "Onboards new team members, manages attendance, and drafts internal communications.",
    skills: ["Onboarding", "Attendance", "Policies", "Comms"],
    responsibilities: ["Team Onboarding", "Attendance Digest", "Policy Drafts", "Internal Comms"],
    outputs: ["Onboarding kits", "Policy drafts", "Attendance digest"],
    color: "from-indigo-100 to-indigo-50 text-indigo-900",
  },
  {
    slug: "ai-support-manager",
    name: "Cleo",
    role: "AI Customer Support Manager",
    icon: LifeBuoy,
    tagline: "Summarises tickets, drafts replies",
    bio: "Summarises open tickets, drafts replies, and flags anything worth escalating.",
    skills: ["Ticket Triage", "Reply Drafts", "SLA", "Escalation"],
    responsibilities: ["Ticket Summaries", "Reply Drafts", "Response Times", "Escalation"],
    outputs: ["Ticket digest", "Reply drafts", "Escalation list"],
    color: "from-cyan-100 to-cyan-50 text-cyan-900",
  },
  {
    slug: "ai-analytics-manager",
    name: "Lume",
    role: "AI Analytics Manager",
    icon: BarChart3,
    tagline: "Builds every recurring report",
    bio: "Assembles weekly, monthly, and campaign reports across growth, courses, and students.",
    skills: ["Reporting", "Dashboards", "Cohorts", "Attribution"],
    responsibilities: [
      "Weekly Reports",
      "Monthly Reports",
      "Growth Reports",
      "Marketing Reports",
      "Course Reports",
      "Student Reports",
    ],
    outputs: ["Weekly report", "Monthly report", "Campaign report"],
    color: "from-blue-100 to-blue-50 text-blue-900",
  },
];

export function findEmployee(slug: string) {
  return AI_EMPLOYEES.find((e) => e.slug === slug);
}
