/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as LaunchYourBrandIndexRouteImport } from './routes/launch-your-brand.index'
import { Route as PartnerApplyRouteImport } from './routes/partner.apply'
import { Route as LaunchYourBrandStartRouteImport } from './routes/launch-your-brand.start'
import { Route as LaunchYourBrandConsultationRouteImport } from './routes/launch-your-brand.consultation'

const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchYourBrandIndexRoute = LaunchYourBrandIndexRouteImport.update({
  id: '/launch-your-brand/',
  path: '/launch-your-brand/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplyRoute = PartnerApplyRouteImport.update({
  id: '/partner/apply',
  path: '/partner/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchYourBrandStartRoute = LaunchYourBrandStartRouteImport.update({
  id: '/launch-your-brand/start',
  path: '/launch-your-brand/start',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchYourBrandConsultationRoute =
  LaunchYourBrandConsultationRouteImport.update({
    id: '/launch-your-brand/consultation',
    path: '/launch-your-brand/consultation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earn': typeof EarnRoute
  '/launch-your-brand/consultation': typeof LaunchYourBrandConsultationRoute
  '/launch-your-brand/start': typeof LaunchYourBrandStartRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/launch-your-brand/': typeof LaunchYourBrandIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earn': typeof EarnRoute
  '/launch-your-brand/consultation': typeof LaunchYourBrandConsultationRoute
  '/launch-your-brand/start': typeof LaunchYourBrandStartRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/launch-your-brand': typeof LaunchYourBrandIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earn': typeof EarnRoute
  '/launch-your-brand/consultation': typeof LaunchYourBrandConsultationRoute
  '/launch-your-brand/start': typeof LaunchYourBrandStartRoute
  '/partner/apply': typeof PartnerApplyRoute
  '/launch-your-brand/': typeof LaunchYourBrandIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/earn'
    | '/launch-your-brand/consultation'
    | '/launch-your-brand/start'
    | '/partner/apply'
    | '/launch-your-brand/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/earn'
    | '/launch-your-brand/consultation'
    | '/launch-your-brand/start'
    | '/partner/apply'
    | '/launch-your-brand'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/earn'
    | '/launch-your-brand/consultation'
    | '/launch-your-brand/start'
    | '/partner/apply'
    | '/launch-your-brand/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarnRoute: typeof EarnRoute
  LaunchYourBrandConsultationRoute: typeof LaunchYourBrandConsultationRoute
  LaunchYourBrandStartRoute: typeof LaunchYourBrandStartRoute
  PartnerApplyRoute: typeof PartnerApplyRoute
  LaunchYourBrandIndexRoute: typeof LaunchYourBrandIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-your-brand/': {
      id: '/launch-your-brand/'
      path: '/launch-your-brand'
      fullPath: '/launch-your-brand/'
      preLoaderRoute: typeof LaunchYourBrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/apply': {
      id: '/partner/apply'
      path: '/partner/apply'
      fullPath: '/partner/apply'
      preLoaderRoute: typeof PartnerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-your-brand/start': {
      id: '/launch-your-brand/start'
      path: '/launch-your-brand/start'
      fullPath: '/launch-your-brand/start'
      preLoaderRoute: typeof LaunchYourBrandStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-your-brand/consultation': {
      id: '/launch-your-brand/consultation'
      path: '/launch-your-brand/consultation'
      fullPath: '/launch-your-brand/consultation'
      preLoaderRoute: typeof LaunchYourBrandConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarnRoute: EarnRoute,
  LaunchYourBrandConsultationRoute: LaunchYourBrandConsultationRoute,
  LaunchYourBrandStartRoute: LaunchYourBrandStartRoute,
  PartnerApplyRoute: PartnerApplyRoute,
  LaunchYourBrandIndexRoute: LaunchYourBrandIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
